// 2026 Texas general-election candidates by district (November 3, 2026 ballot).
// Sources: Wikipedia 2026 TX U.S. House / State House / State Senate election pages,
// cross-checked against Ballotpedia. Compiled July 2026 (post March-3 primary & May-26 runoff).
// Congressional districts use Plan C2333; SBOE uses Plan E2106. Party codes: D, R, L (Libertarian), G (Green), I (Independent).
// "inc":true marks the sitting incumbent running. Empty/one-sided races = uncontested by the other major party.
// C = U.S. Congress, H = State House, S = State Senate, E = State Board of Education (SBOE).
// S and E have staggered terms: only "up2026" districts are on the ballot; others show the sitting member (see "current" for E).
window.TX_CAND_2026 = {
  "C": {
    "1": {"cands":[{"n":"Nathaniel Moran","p":"R","inc":true},{"n":"Sonia Canchola","p":"I"}]},
    "2": {"cands":[{"n":"Steve Toth","p":"R"},{"n":"Shaun Finnie","p":"D"}]},
    "3": {"cands":[{"n":"Keith Self","p":"R","inc":true},{"n":"Evan Hunt","p":"D"}]},
    "4": {"cands":[{"n":"Pat Fallon","p":"R","inc":true},{"n":"Jason Pearce","p":"D"}]},
    "5": {"cands":[{"n":"Lance Gooden","p":"R","inc":true},{"n":"Dea Foy","p":"D"}]},
    "6": {"cands":[{"n":"Jake Ellzey","p":"R","inc":true},{"n":"Danny Minton","p":"D"}]},
    "7": {"cands":[{"n":"Lizzie Fletcher","p":"D","inc":true},{"n":"Alexander Hale","p":"R"},{"n":"Espoir Ngabo","p":"G"}]},
    "8": {"cands":[{"n":"Jessica Steinmann","p":"R"},{"n":"Laura Jones","p":"D"}]},
    "9": {"cands":[{"n":"Alex Mealer","p":"R"},{"n":"Leticia Gutierrez","p":"D"},{"n":"Roy Morales","p":"I"}]},
    "10": {"cands":[{"n":"Chris Gober","p":"R"},{"n":"Caitlin Rourk","p":"D"}]},
    "11": {"cands":[{"n":"August Pfluger","p":"R","inc":true},{"n":"Claire Reynolds","p":"D"}]},
    "12": {"cands":[{"n":"Craig Goldman","p":"R","inc":true},{"n":"Heli Rodriguez Prilliman","p":"D"}]},
    "13": {"cands":[{"n":"Ronny Jackson","p":"R","inc":true},{"n":"Mark Nair","p":"D"}]},
    "14": {"cands":[{"n":"Randy Weber","p":"R","inc":true},{"n":"Thurman Bill Bartie","p":"D"}]},
    "15": {"cands":[{"n":"Monica De La Cruz","p":"R","inc":true},{"n":"Bobby Pulido","p":"D"}]},
    "16": {"cands":[{"n":"Veronica Escobar","p":"D","inc":true},{"n":"Adam Bauman","p":"R"}]},
    "17": {"cands":[{"n":"Pete Sessions","p":"R","inc":true},{"n":"Casey Shepard","p":"D"}]},
    "18": {"cands":[{"n":"Christian Menefee","p":"D","inc":true},{"n":"Ronald Whitfield","p":"R"}]},
    "19": {"cands":[{"n":"Tom Sell","p":"R"},{"n":"Kyle Rable","p":"D"},{"n":"Michael Garcia","p":"I"}]},
    "20": {"cands":[{"n":"Joaquin Castro","p":"D","inc":true},{"n":"Edgardo Baez","p":"R"},{"n":"Anthony Tristan","p":"I"}]},
    "21": {"cands":[{"n":"Mark Teixeira","p":"R"},{"n":"Kristin Hook","p":"D"},{"n":"Dan McQueen","p":"I"}]},
    "22": {"cands":[{"n":"Trever Nehls","p":"R"},{"n":"Marquette Greene-Scott","p":"D"},{"n":"Demile James","p":"I"}]},
    "23": {"cands":[{"n":"Brandon Herrera","p":"R"},{"n":"Katy Padilla Stout","p":"D"},{"n":"Patti Hale Ashe","p":"I"},{"n":"Veronica Williams","p":"I"}]},
    "24": {"cands":[{"n":"Beth Van Duyne","p":"R","inc":true},{"n":"Kevin Burge","p":"D"}]},
    "25": {"cands":[{"n":"Roger Williams","p":"R","inc":true},{"n":"Dione Sims","p":"D"}]},
    "26": {"cands":[{"n":"Brandon Gill","p":"R","inc":true},{"n":"Steven Shook","p":"D"},{"n":"Phil Gray","p":"L"}]},
    "27": {"cands":[{"n":"Michael Cloud","p":"R","inc":true},{"n":"Tanya Lloyd","p":"D"}]},
    "28": {"cands":[{"n":"Henry Cuellar","p":"D","inc":true},{"n":"Tano Tijerina","p":"R"},{"n":"Adriel Ventura Lopez","p":"I"}]},
    "29": {"cands":[{"n":"Sylvia Garcia","p":"D","inc":true},{"n":"Martha Fierro","p":"R"}]},
    "30": {"cands":[{"n":"Frederick Haynes","p":"D"},{"n":"Everett Jackson","p":"R"},{"n":"Oxford Nordberg","p":"I"}]},
    "31": {"cands":[{"n":"John Carter","p":"R","inc":true},{"n":"Justin Early","p":"D"},{"n":"Greg Stoker","p":"G"},{"n":"Larice Woods","p":"I"}]},
    "32": {"cands":[{"n":"Dan Barrios","p":"D"},{"n":"Jace Yarbrough","p":"R"},{"n":"Charles Harper","p":"I"}]},
    "33": {"cands":[{"n":"Colin Allred","p":"D"},{"n":"Patrick Gillespie","p":"R"},{"n":"Brent Brown","p":"I"}]},
    "34": {"cands":[{"n":"Vicente Gonzalez Jr.","p":"D","inc":true},{"n":"Eric Flores","p":"R"},{"n":"Eddie Espinoza","p":"G"},{"n":"Chris Royal","p":"L"}]},
    "35": {"cands":[{"n":"Johnny Garcia","p":"D"},{"n":"Carlos De La Cruz","p":"R"}]},
    "36": {"cands":[{"n":"Brian Babin","p":"R","inc":true},{"n":"Rhonda Hart","p":"D"},{"n":"Hal Ridley","p":"I"}]},
    "37": {"cands":[{"n":"Greg Casar","p":"D","inc":true},{"n":"Lauren Peña","p":"R"},{"n":"James Kinney","p":"I"}]},
    "38": {"cands":[{"n":"Melissa McDonough","p":"D"},{"n":"Jon Bonck","p":"R"},{"n":"Alex McMenemy","p":"G"}]}
  },
  "H": {
    "1": {"cands":[{"n":"Chris Spencer","p":"R"},{"n":"Sean Huffman","p":"D"}]},
    "2": {"cands":[{"n":"Brent Money","p":"R","inc":true},{"n":"Fatima La'Juan Muse","p":"D"}]},
    "3": {"cands":[{"n":"Kristen Plaisance","p":"R"},{"n":"Nicole King","p":"D"}]},
    "4": {"cands":[{"n":"Keith Bell","p":"R","inc":true},{"n":"Mark A. Moseley","p":"D"}]},
    "5": {"cands":[{"n":"Cole Hefner","p":"R","inc":true},{"n":"Hector Garza","p":"D"}]},
    "6": {"cands":[{"n":"Daniel Alders","p":"R","inc":true},{"n":"Lorenzo Johnson","p":"D"}]},
    "7": {"cands":[{"n":"Jay Dean","p":"R","inc":true},{"n":"Fantasha Allen","p":"D"}]},
    "8": {"cands":[{"n":"Cody Harris","p":"R","inc":true},{"n":"Jeff Chavez","p":"D"}]},
    "9": {"cands":[{"n":"Rocky Thigpen","p":"R"},{"n":"Shelly Tatum","p":"D"}]},
    "10": {"cands":[{"n":"Brian Harrison","p":"R","inc":true},{"n":"Michael Myers","p":"D"}]},
    "11": {"cands":[{"n":"Joanne Shofner","p":"R","inc":true},{"n":"Roxanne Lathan","p":"D"}]},
    "12": {"cands":[{"n":"Trey Wharton","p":"R","inc":true},{"n":"Andie Ho","p":"D"}]},
    "13": {"cands":[{"n":"Angelia Orr","p":"R","inc":true},{"n":"Albert Hunter","p":"D"}]},
    "14": {"cands":[{"n":"Paul Dyson","p":"R","inc":true},{"n":"Janet Tycelia Dudding","p":"D"},{"n":"Jeff Miller","p":"L"}]},
    "15": {"cands":[{"n":"Brad Bailey","p":"R"},{"n":"Moniqua S. Scott","p":"D"},{"n":"Jessi Cowart","p":"L"}]},
    "16": {"cands":[{"n":"Will Metcalf","p":"R","inc":true},{"n":"Bobby Clayton","p":"D"}]},
    "17": {"cands":[{"n":"Stan Gerdes","p":"R","inc":true},{"n":"Mary Elizabeth Klenz","p":"D"}]},
    "18": {"cands":[{"n":"Janis Holt","p":"R","inc":true},{"n":"Valorie Barton","p":"D"}]},
    "19": {"cands":[{"n":"Ellen Troxclair","p":"R","inc":true},{"n":"Kelly Hall","p":"D"}]},
    "20": {"cands":[{"n":"Terry Wilson","p":"R","inc":true},{"n":"Matthias-Jonah Early","p":"D"}]},
    "21": {"cands":[{"n":"Ray Callas","p":"R"},{"n":"Jacqueline \"Jacky\" Hernandez","p":"D"}]},
    "22": {"cands":[{"n":"Christian Manuel","p":"D","inc":true}]},
    "23": {"cands":[{"n":"Terri Leo-Wilson","p":"R","inc":true},{"n":"Cheryl Lynn Clark","p":"D"}]},
    "24": {"cands":[{"n":"Greg Bonnen","p":"R","inc":true},{"n":"Frank N. Carr","p":"D"}]},
    "25": {"cands":[{"n":"Cody Vasut","p":"R","inc":true},{"n":"Mike Meadors","p":"D"}]},
    "26": {"cands":[{"n":"Matt Morgan","p":"R","inc":true},{"n":"Elizabeth \"Liz\" Markowitz","p":"D"}]},
    "27": {"cands":[{"n":"Ron Reynolds","p":"D","inc":true},{"n":"Max Alalibo","p":"R"}]},
    "28": {"cands":[{"n":"Gary Gates","p":"R","inc":true},{"n":"Sandy Ibanez","p":"D"}]},
    "29": {"cands":[{"n":"Jeff Barry","p":"R","inc":true},{"n":"Karen Reeder","p":"D"}]},
    "30": {"cands":[{"n":"AJ Louderback","p":"R","inc":true},{"n":"Crystal Sedillo","p":"D"}]},
    "31": {"cands":[{"n":"Ryan Guillen","p":"R","inc":true},{"n":"Jennifer \"JJ\" Dominguez","p":"D"}]},
    "32": {"cands":[{"n":"Todd Hunter","p":"R","inc":true},{"n":"Gabriel Lazano Marroquin","p":"D"}]},
    "33": {"cands":[{"n":"Katrina Pierson","p":"R","inc":true},{"n":"Orlando Lopez","p":"D"}]},
    "34": {"cands":[{"n":"Denise Villalobos","p":"R","inc":true},{"n":"Stephanie Guerrero Saenz","p":"D"}]},
    "35": {"cands":[{"n":"Oscar Longoria","p":"D","inc":true},{"n":"Oscar Rosa","p":"R"}]},
    "36": {"cands":[{"n":"Sergio Muñoz","p":"D","inc":true}]},
    "37": {"cands":[{"n":"Janie Lopez","p":"R","inc":true},{"n":"Oziel \"Ozzie\" Ochoa, Jr.","p":"D"}]},
    "38": {"cands":[{"n":"Erin Gamez","p":"D","inc":true},{"n":"Laura E. Cisneros","p":"R"}]},
    "39": {"cands":[{"n":"Armando Martinez","p":"D","inc":true}]},
    "40": {"cands":[{"n":"Terry Canales","p":"D","inc":true},{"n":"Celeste Cabrera-Huff","p":"R"}]},
    "41": {"cands":[{"n":"Julio Salinas","p":"D"},{"n":"Gary Groves","p":"R"}]},
    "42": {"cands":[{"n":"Richard Raymond","p":"D","inc":true},{"n":"Teresa Johnson-Hernandez","p":"R"}]},
    "43": {"cands":[{"n":"José Manuel Lozano","p":"R","inc":true},{"n":"Jeffrey T. Jackson","p":"D"}]},
    "44": {"cands":[{"n":"Alan Schoolcraft","p":"R","inc":true},{"n":"Eric Norman","p":"D"}]},
    "45": {"cands":[{"n":"Erin Zwiener","p":"D","inc":true},{"n":"Tennyson G. Moreno","p":"R"}]},
    "46": {"cands":[{"n":"Sheryl Cole","p":"D","inc":true}]},
    "47": {"cands":[{"n":"Pooja Sethi","p":"D"},{"n":"Jennifer Mushtaler","p":"R"}]},
    "48": {"cands":[{"n":"Donna Howard","p":"D","inc":true},{"n":"Anthony Gupta","p":"R"}]},
    "49": {"cands":[{"n":"Montserrat Garibay","p":"D"},{"n":"Arshia Papari","p":"G"}]},
    "50": {"cands":[{"n":"Samantha Lopez Resendez","p":"D"},{"n":"Howard Olsen","p":"R"}]},
    "51": {"cands":[{"n":"Lulu Flores","p":"D","inc":true},{"n":"Jessica Martinez","p":"R"}]},
    "52": {"cands":[{"n":"Caroline Harris Davila","p":"R","inc":true},{"n":"Chris Jimenez","p":"D"}]},
    "53": {"cands":[{"n":"Wes Virdell","p":"R","inc":true},{"n":"Kathryn Hartmann","p":"D"}]},
    "54": {"cands":[{"n":"Brad Buckley","p":"R","inc":true},{"n":"Dawn Richardson","p":"D"}]},
    "55": {"cands":[{"n":"Hillary Hickland","p":"R","inc":true},{"n":"Amelia Rabroker","p":"D"}]},
    "56": {"cands":[{"n":"Pat Curry","p":"R","inc":true},{"n":"Ashley Bean Thornton","p":"D"}]},
    "57": {"cands":[{"n":"Richard Hayes","p":"R","inc":true},{"n":"Ray Smith","p":"D"},{"n":"Darren Hamilton","p":"L"}]},
    "58": {"cands":[{"n":"Helen Kerwin","p":"R","inc":true},{"n":"Chris Oldham","p":"D"}]},
    "59": {"cands":[{"n":"Shelby Slawson","p":"R","inc":true},{"n":"Andrew Turner","p":"D"}]},
    "60": {"cands":[{"n":"Mike Olcott","p":"R","inc":true},{"n":"Krissy Guess","p":"D"}]},
    "61": {"cands":[{"n":"Keresa Richardson","p":"R","inc":true},{"n":"Brittany Black","p":"D"},{"n":"Anissa Chilmeran","p":"G"}]},
    "62": {"cands":[{"n":"Shelley Luther","p":"R","inc":true},{"n":"Catherine Thorne","p":"D"}]},
    "63": {"cands":[{"n":"Ben Bumgarner","p":"R","inc":true},{"n":"Denise Wooten","p":"D"}]},
    "64": {"cands":[{"n":"Andy Hopper","p":"R","inc":true},{"n":"Julie Evans","p":"D"}]},
    "65": {"cands":[{"n":"Mitch Little","p":"R","inc":true},{"n":"Detrick Beburr","p":"D"}]},
    "66": {"cands":[{"n":"Matt Shaheen","p":"R","inc":true},{"n":"Sandeep Srivastava","p":"D"}]},
    "67": {"cands":[{"n":"Jeff Leach","p":"R","inc":true},{"n":"Jordan Wheatley","p":"D"}]},
    "68": {"cands":[{"n":"David Spiller","p":"R","inc":true},{"n":"Jasmine Henderson","p":"D"}]},
    "69": {"cands":[{"n":"James Frank","p":"R","inc":true},{"n":"Leilani Barnett","p":"D"}]},
    "70": {"cands":[{"n":"Mihaela Plesa","p":"D","inc":true},{"n":"George Flint","p":"R"}]},
    "71": {"cands":[{"n":"Jay Hardaway","p":"R"},{"n":"Chance Ferguson","p":"D"}]},
    "72": {"cands":[{"n":"Drew Darby","p":"R","inc":true},{"n":"Shiloh Salazar","p":"D"}]},
    "73": {"cands":[{"n":"Carrie Isaac","p":"R","inc":true},{"n":"Merrie Fox","p":"D"}]},
    "74": {"cands":[{"n":"Eddie Morales","p":"D","inc":true},{"n":"Robert Garza","p":"R"}]},
    "75": {"cands":[{"n":"Mary González","p":"D","inc":true}]},
    "76": {"cands":[{"n":"Suleman Lalani","p":"D","inc":true},{"n":"Linda Howell","p":"R"}]},
    "77": {"cands":[{"n":"Vincent Perez","p":"D","inc":true},{"n":"Humberto Perez","p":"R"}]},
    "78": {"cands":[{"n":"Joe Moody","p":"D","inc":true}]},
    "79": {"cands":[{"n":"Claudia Ordaz","p":"D","inc":true},{"n":"Jesus Romero","p":"R"}]},
    "80": {"cands":[{"n":"Don McLaughlin","p":"R","inc":true},{"n":"Cecilia Castellano","p":"D"}]},
    "81": {"cands":[{"n":"Brooks Landgraf","p":"R","inc":true},{"n":"Ceasar Sanchez","p":"D"}]},
    "82": {"cands":[{"n":"Tom Craddick","p":"R","inc":true},{"n":"Cathy Broadrick","p":"D"}]},
    "83": {"cands":[{"n":"Dustin Burrows","p":"R","inc":true},{"n":"Malik Williams","p":"D"}]},
    "84": {"cands":[{"n":"Carl Tepper","p":"R","inc":true},{"n":"Maggie Durham","p":"D"}]},
    "85": {"cands":[{"n":"Dennis \"Goose\" Geesaman","p":"R"},{"n":"Lawrence Brandyburg","p":"D"}]},
    "86": {"cands":[{"n":"Holly Jeffreys","p":"R"},{"n":"Cullin Knutson","p":"D"}]},
    "87": {"cands":[{"n":"Caroline Fairly","p":"R","inc":true},{"n":"Diana Loya","p":"D"}]},
    "88": {"cands":[{"n":"Ken King","p":"R","inc":true},{"n":"Heather J. Wallace","p":"D"}]},
    "89": {"cands":[{"n":"Candy Noble","p":"R","inc":true},{"n":"Angie Carraway","p":"D"}]},
    "90": {"cands":[{"n":"Ramon Romero Jr.","p":"D","inc":true}]},
    "91": {"cands":[{"n":"David Lowe","p":"R","inc":true},{"n":"Yisak Worku","p":"D"}]},
    "92": {"cands":[{"n":"Salman Bhojani","p":"D","inc":true},{"n":"J.P. Woodruff","p":"R"}]},
    "93": {"cands":[{"n":"Alan Blaylock","p":"R"},{"n":"Ericka Lomick","p":"D"}]},
    "94": {"cands":[{"n":"Cheryl Bean","p":"R"},{"n":"Katie O'Brien Duzan","p":"D"}]},
    "95": {"cands":[{"n":"Nicole Collier","p":"D","inc":true}]},
    "96": {"cands":[{"n":"Ellen Fleischmann","p":"R"},{"n":"Ebony Turner","p":"D"}]},
    "97": {"cands":[{"n":"John McQueeney","p":"R","inc":true},{"n":"Beth Llewellyn McLaughlin","p":"D"}]},
    "98": {"cands":[{"n":"Armin Mizani","p":"R"},{"n":"Cate Brennan","p":"D"}]},
    "99": {"cands":[{"n":"Charlie Geren","p":"R","inc":true},{"n":"Michelle Winder","p":"D"}]},
    "100": {"cands":[{"n":"Venton Jones","p":"D","inc":true},{"n":"Jordan Hoffnagle","p":"R"}]},
    "101": {"cands":[{"n":"Junior Ezeonu","p":"D"}]},
    "102": {"cands":[{"n":"Ana-Maria Ramos","p":"D","inc":true},{"n":"Bonnie Abadie","p":"R"}]},
    "103": {"cands":[{"n":"Rafael Anchia","p":"D","inc":true},{"n":"Melanie Medley-Thomas","p":"R"}]},
    "104": {"cands":[{"n":"Jessica Gonzalez","p":"D","inc":true}]},
    "105": {"cands":[{"n":"Terry Meza","p":"D","inc":true}]},
    "106": {"cands":[{"n":"Jared Patterson","p":"R","inc":true},{"n":"Joe Mayes","p":"D"}]},
    "107": {"cands":[{"n":"Linda Garcia","p":"D","inc":true}]},
    "108": {"cands":[{"n":"Morgan Meyer","p":"R","inc":true},{"n":"Allison Mitchell","p":"D"}]},
    "109": {"cands":[{"n":"Aicha Davis","p":"D","inc":true},{"n":"Will Campbell","p":"R"}]},
    "110": {"cands":[{"n":"Toni Rose","p":"D","inc":true}]},
    "111": {"cands":[{"n":"Yvonne Davis","p":"D","inc":true}]},
    "112": {"cands":[{"n":"Angie Chen Button","p":"R","inc":true},{"n":"Zach Herbert","p":"D"}]},
    "113": {"cands":[{"n":"Rhetta Andrews Bowers","p":"D","inc":true},{"n":"Stephen Stanley","p":"R"}]},
    "114": {"cands":[{"n":"John W. Bryant","p":"D","inc":true},{"n":"Tim McDonough","p":"R"}]},
    "115": {"cands":[{"n":"Cassandra Garcia Hernandez","p":"D","inc":true},{"n":"Danny Rosellini","p":"R"},{"n":"Kane Kelly","p":"I"}]},
    "116": {"cands":[{"n":"Trey Martinez Fischer","p":"D","inc":true},{"n":"Rhett Rosenquest Smith","p":"R"}]},
    "117": {"cands":[{"n":"Philip Cortez","p":"D","inc":true},{"n":"Ben Mostyn","p":"R"}]},
    "118": {"cands":[{"n":"Kristian Carranza","p":"D"},{"n":"Jorge Borrego","p":"R"}]},
    "119": {"cands":[{"n":"Elizabeth Campos","p":"D","inc":true},{"n":"Melva Perez","p":"R"}]},
    "120": {"cands":[{"n":"Barbara Gervin-Hawkins","p":"D","inc":true}]},
    "121": {"cands":[{"n":"Marc LaHood","p":"R","inc":true},{"n":"Zack Dunn","p":"D"}]},
    "122": {"cands":[{"n":"Mark Dorazio","p":"R","inc":true},{"n":"Shelly Nickels","p":"D"}]},
    "123": {"cands":[{"n":"Diego Bernal","p":"D","inc":true}]},
    "124": {"cands":[{"n":"Josey Garcia","p":"D","inc":true},{"n":"Sylvia Soto","p":"R"},{"n":"L.D. Howard","p":"I"}]},
    "125": {"cands":[{"n":"Adrian Reyna","p":"D"},{"n":"Ricardo Martinez","p":"R"}]},
    "126": {"cands":[{"n":"Stefanie Bord","p":"D"},{"n":"Stan Stanart","p":"R"},{"n":"Lisa Emerson","p":"I"}]},
    "127": {"cands":[{"n":"Charles Cunningham","p":"R","inc":true},{"n":"Michelle Williams","p":"D"}]},
    "128": {"cands":[{"n":"Tom Butler","p":"R"},{"n":"Desiree Klaus","p":"D"}]},
    "129": {"cands":[{"n":"Scott Bowen","p":"R"},{"n":"Albert Wittliff","p":"D"}]},
    "130": {"cands":[{"n":"Tom Oliverson","p":"R","inc":true},{"n":"Brett Robinson","p":"D"}]},
    "131": {"cands":[{"n":"Staci Childs","p":"D"},{"n":"Scott Whitmarsh","p":"R"}]},
    "132": {"cands":[{"n":"Mike Schofield","p":"R","inc":true},{"n":"Sara McGee","p":"D"}]},
    "133": {"cands":[{"n":"Mano Deayala","p":"R","inc":true},{"n":"Josh Wallenstein","p":"D"}]},
    "134": {"cands":[{"n":"Ann Johnson","p":"D","inc":true},{"n":"Mike Michna","p":"R"}]},
    "135": {"cands":[{"n":"Odus Evbagharu","p":"D"},{"n":"Liz Ramos","p":"R"}]},
    "136": {"cands":[{"n":"John Bucy III","p":"D","inc":true},{"n":"Theodore Schramm","p":"R"}]},
    "137": {"cands":[{"n":"Gene Wu","p":"D","inc":true},{"n":"Helen Zhou","p":"R"}]},
    "138": {"cands":[{"n":"Lacey Hull","p":"R","inc":true},{"n":"Tyler Smith","p":"D"}]},
    "139": {"cands":[{"n":"Charlene Ward Johnson","p":"D","inc":true},{"n":"Kyle Harding","p":"R"}]},
    "140": {"cands":[{"n":"Armando Walle","p":"D","inc":true},{"n":"Laura Garcia DeLeon","p":"R"}]},
    "141": {"cands":[{"n":"Senfronia Thompson","p":"D","inc":true},{"n":"Julie Hunt","p":"R"}]},
    "142": {"cands":[{"n":"Harold Dutton Jr.","p":"D","inc":true},{"n":"Heidi Hall","p":"R"}]},
    "143": {"cands":[{"n":"Ana Hernandez","p":"D","inc":true},{"n":"Frank Salazar","p":"R"}]},
    "144": {"cands":[{"n":"Mary Ann Perez","p":"D","inc":true},{"n":"David Flores","p":"R"}]},
    "145": {"cands":[{"n":"Christina Morales","p":"D","inc":true},{"n":"Inocensia Moreno","p":"R"}]},
    "146": {"cands":[{"n":"Lauren Ashley Simmons","p":"D","inc":true},{"n":"Alexandria Butler","p":"R"}]},
    "147": {"cands":[{"n":"Jolanda Jones","p":"D","inc":true},{"n":"Theodis Daniel","p":"R"}]},
    "148": {"cands":[{"n":"Penny Morales Shaw","p":"D","inc":true},{"n":"Amanda LaBrie","p":"R"}]},
    "149": {"cands":[{"n":"Darlene Breaux","p":"D"},{"n":"Dave Bennett","p":"R"}]},
    "150": {"cands":[{"n":"Valoree Swanson","p":"R","inc":true},{"n":"A'Yonna Kellum","p":"D"}]}
  },
  "S": {
    "up2026": [1, 2, 3, 4, 5, 9, 11, 13, 18, 19, 21, 22, 24, 26, 28, 31],
    "races": {
      "1": {"cands":[{"n":"Bryan Hughes","p":"R","inc":true},{"n":"Laticia Ambroz","p":"D"}]},
      "2": {"cands":[{"n":"Bob Hall","p":"R","inc":true},{"n":"Keenen Colbert","p":"D"}]},
      "3": {"cands":[{"n":"Trent Ashby","p":"R"},{"n":"Bobby Tillman","p":"D"}]},
      "4": {"cands":[{"n":"Brett Ligon","p":"R","inc":true},{"n":"Ron Angeletti","p":"D"}]},
      "5": {"cands":[{"n":"Charles Schwertner","p":"R","inc":true},{"n":"Paul Thomasson","p":"D"}]},
      "9": {"cands":[{"n":"Taylor Rehmet","p":"D","inc":true},{"n":"Leigh Wambsganss","p":"R"}]},
      "11": {"cands":[{"n":"Dennis Paul","p":"R"},{"n":"Shannon Dicely","p":"D"}]},
      "13": {"cands":[{"n":"Borris Miles","p":"D","inc":true}]},
      "18": {"cands":[{"n":"Lois Kolkhorst","p":"R","inc":true},{"n":"Erica Gillum","p":"D"}]},
      "19": {"cands":[{"n":"Roland Gutierrez","p":"D","inc":true},{"n":"Marcus Cardenas","p":"R"}]},
      "21": {"cands":[{"n":"Judith Zaffirini","p":"D","inc":true},{"n":"Julie Dahlberg","p":"R"}]},
      "22": {"cands":[{"n":"David Cook","p":"R"},{"n":"Amy Martinez-Salas","p":"D"}]},
      "24": {"cands":[{"n":"Pete Flores","p":"R","inc":true},{"n":"Joe Herrera","p":"D"}]},
      "26": {"cands":[{"n":"José Menéndez","p":"D","inc":true},{"n":"Julián Villarreal","p":"G"}]},
      "28": {"cands":[{"n":"Charles Perry","p":"R","inc":true},{"n":"Riley Rodriquez","p":"D"}]},
      "31": {"cands":[{"n":"Kevin Sparks","p":"R","inc":true},{"n":"John Betancourt","p":"D"}]}
    }
  },
  "E": {
    "up2026": [2, 5, 6, 7, 8, 9, 13, 14],
    "current": {
      "1": {"n":"Gustavo Reveles","p":"D"},
      "2": {"n":"LJ Francis","p":"R"},
      "3": {"n":"Marisa Perez-Diaz","p":"D"},
      "4": {"n":"Staci Childs","p":"D"},
      "5": {"n":"Rebecca Bell-Metereau","p":"D"},
      "6": {"n":"Will Hickman","p":"R"},
      "7": {"n":"Julie Pickren","p":"R"},
      "8": {"n":"Audrey Young","p":"R"},
      "9": {"n":"Keven Ellis","p":"R"},
      "10": {"n":"Tom Maynard","p":"R"},
      "11": {"n":"Brandon Hall","p":"R"},
      "12": {"n":"Pam Little","p":"R"},
      "13": {"n":"Tiffany Clark","p":"D"},
      "14": {"n":"Evelyn Brooks","p":"R"},
      "15": {"n":"Aaron Kinsey","p":"R"}
    },
    "races": {
      "2": {"cands":[{"n":"Victoria Hinojosa","p":"R"},{"n":"Thomas Garcia","p":"D"}]},
      "5": {"cands":[{"n":"Mica Arellano","p":"R"},{"n":"Allison Bush","p":"D"}]},
      "6": {"cands":[{"n":"Tiffany Nelson","p":"R"},{"n":"Michelle Palmer","p":"D"}]},
      "7": {"cands":[{"n":"Julie Pickren","p":"R","inc":true},{"n":"Tiffany Perkinz","p":"D"}]},
      "8": {"cands":[{"n":"Audrey Young","p":"R","inc":true},{"n":"Dana Van De Walker","p":"D"}]},
      "9": {"cands":[{"n":"Kason Huddleston","p":"R"},{"n":"Ericka Ledferd","p":"D"}]},
      "13": {"cands":[{"n":"Tiffany Clark","p":"D","inc":true},{"n":"April Williams Moore","p":"R"}]},
      "14": {"cands":[{"n":"Mindy Bumgarner","p":"R"},{"n":"Amy Taylor","p":"D"}]}
    }
  }
};
