/* tx_deep_dive.js — the county command center (texas_county_deep_dive.html) on the tx_county_map.js engine.
   Opens on a Texas page (statewide What to know, ranked lists, the statewide ballot); search or click a county → What to know (statements with the
   numbers underneath) → tabs (Overview, Elections, Money, Ballot, Community, Districts, Water, Data Centers)
   → Compare tray (up to three counties) → Prepare roundtable (a one-page brief with source links). Version 20260928-12. */
(function(){
const {esc,num,cname}=CM,$=id=>document.getElementById(id);
const DM=window.TX_COUNTY_DEMOGRAPHICS||{},TXD=window.TX_DEMOGRAPHICS_STATE||{},E=window.TX_COUNTY_ELECTIONS||{state:{},counties:{}},S=E.state,X=window.TX_DISTRICT_XW||{counties:{},changed:{},county_pop:{},plans:{}},R=window.TX_DISTRICT_RESULTS||{},B=window.TX_COUNTY_BALLOT||{offices:[],cands:[],counties:{}},O=window.TX_COUNTY_ORGS||{orgs:[],waves:[]},WD=window.TX_COUNTY_WATER||{counties:{}},W=WD.counties||{},AQ=window.TX_COUNTY_AQUIFERS||{},DC=(window.TX_DC_SITES||[]).filter(s=>s.kind==='project'),PL=window.TX_PLACES||[],RG=window.TX_REGIONS||{};
const F=Object.keys(E.counties).filter(f=>DM[f]);const NEW='PLANC2333',OLD='PLANC2193';
const d=(f,k)=>f==='48'?TXD[k]:(DM[f]?DM[f][k]:null),e=(f,k)=>f==='48'?S[k]:(E.counties[f]?E.counties[f][k]:null);
const PCT=v=>(v*100).toFixed(1)+'%',PCT0=v=>Math.round(v*100)+'%',PTS=v=>(v>0?'+':'')+(v*100).toFixed(1)+' pts',SPCT=v=>(v>0?'+':'')+(v*100).toFixed(1)+'%',USD=v=>'$'+num(Math.round(v)),USDK=v=>v>=1e6?'$'+(v/1e6).toFixed(1)+'M':v>=1e3?'$'+Math.round(v/1e3)+'k':'$'+Math.round(v),RM=v=>(v>0?'R +':v<0?'D +':'')+Math.abs(v*100).toFixed(1);
const CT=window.TX_COUNTY_CONTRIBS||{cands:{},spacs:{}};const shareOf=(x,cd)=>(cd[3]&&!cd[8])?(x/cd[3]<0.01?'under 1%':PCT0(Math.min(1,x/cd[3]))):'';const CIDX=new Map(B.cands.map((c,i)=>[c,String(i)]));
// contributions from a county's donors to one candidate: [dollars 2026 YTD, n, dollars since 2025, n] (candidate account + linked committees)
const fromCounty=(cd,f)=>{const i=CIDX.get(cd);const a=(CT.cands[i]||{})[f],b=(CT.spacs[i]||{})[f];if(!a&&!b)return null;const o=[0,0,0,0];[a,b].forEach(x=>{if(x)x.forEach((v,k)=>o[k]+=v);});return o;};
const NAMES={pres:{2008:['McCain','Obama'],2012:['Romney','Obama'],2016:['Trump','Clinton'],2020:['Trump','Biden'],2024:['Trump','Harris']},gov:{2006:['Perry','Bell'],2010:['Perry','White'],2014:['Abbott','Davis'],2018:['Abbott','Valdez'],2022:['Abbott',"O'Rourke"]},sen:{2006:['Hutchison','Radnofsky'],2008:['Cornyn','Noriega'],2012:['Cruz','Sadler'],2014:['Cornyn','Alameel'],2018:['Cruz',"O'Rourke"],2020:['Cornyn','Hegar'],2024:['Cruz','Allred']}};
const RMN=(v,y,race)=>{const n=(NAMES[race]||{})[y];if(v==null||isNaN(v))return '—';if(!n)return RM(v);const a=Math.abs(v*100).toFixed(1);return v>0?n[0]+' +'+a:v<0?n[1]+' +'+a:'even';};
const dres=(plan,y,n)=>R[plan]&&R[plan].years[y]&&R[plan].years[y].d[n];const marg=(plan,y,race,n)=>{const r=dres(plan,y,n);return r&&r[race]?r[race][0]-r[race][1]:null;};const names=(plan,y,race)=>(R[plan]&&R[plan].years[y]&&R[plan].years[y].names[race])||['Rep.','Dem.'];
const lean=(plan,f,y=2024,race='pres')=>{let s=0,w=0;((X.counties[f]||{})[plan]||[]).forEach(([n,p,sh])=>{const m=marg(plan,y,race,n);if(m!=null){s+=m*sh;w+=sh;}});return w?s/w:null;};
// ---- derived per county ----
const ORG={};(O.orgs||[]).forEach(o=>{(ORG[o.f]=ORG[o.f]||[]).push(o);});const CATS=['Agriculture','Teachers','Labor','Business','Health','Faith','Veterans','Higher ed','Civic','Parents/families','Industry-specific'];
const DOWN=new Set(['State district','Judicial district','District attorney']);const raceTot={};B.cands.forEach(c=>{const o=B.offices[c[1]];if(DOWN.has(o[1])&&c[3]!=null)raceTot[o[0]]=(raceTot[o[0]]||0)+c[3];});
const legTot=Object.keys(raceTot).filter(k=>B.offices.some(o=>o[0]===k&&o[1]==='State district')).map(k=>raceTot[k]).sort((a,b)=>a-b);const HIGH=legTot.length?legTot[Math.floor(legTot.length*0.75)]:Infinity;
const DCC={};DC.forEach(s=>{if(s.status==='withdrawn')return;(DCC[s.fips]=DCC[s.fips]||[]).push(s);});
const V={};F.forEach(f=>{const c=E.counties[f];const v=V[f]={};v.leanNew=lean(NEW,f);v.leanOld=lean(OLD,f);v.leanChg=(v.leanNew!=null&&v.leanOld!=null)?v.leanNew-v.leanOld:null;v.regVsPop=(c.registration_growth_2020_2024!=null&&d(f,'Pop. change 2020-2025 (%)')!=null)?c.registration_growth_2020_2024-d(f,'Pop. change 2020-2025 (%)'):null;
  v.regSince22=(c.registered_2022&&c.registered_2024)?c.registered_2024/c.registered_2022-1:null;v.adults=d(f,'Adults 18+ (ACS 2020-24)');v.regOfAdults=(v.adults&&(c.registered_march_2026||c.registered_2024))?(c.registered_march_2026||c.registered_2024)/v.adults:null;v.cdChg=X.changed[f]||0;
  let money=0,n=0;const bc=B.counties[f];if(bc)bc.cands.forEach(i=>{const cd=B.cands[i],o=B.offices[cd[1]];if(DOWN.has(o[1])&&cd[3]!=null){money+=cd[3];n++;}});v.money=money;v.moneyN=n;
  let ct=0,ctn=0,cD=0,cR=0,gD=0,gR=0;const addc=(i,x)=>{ct+=x[0];ctn+=x[1];const cd=B.cands[+i];if(cd[2]==='DEM')cD+=x[0];else if(cd[2]==='REP')cR+=x[0];if(B.offices[cd[1]][0]==='GOVERNOR'){if(cd[2]==='DEM')gD+=x[0];else if(cd[2]==='REP')gR+=x[0];}};Object.keys(CT.cands).forEach(i=>{const x=CT.cands[i][f];if(x)addc(i,x);});Object.keys(CT.spacs).forEach(i=>{const x=CT.spacs[i][f];if(x)addc(i,x);});v.contrib=ct;v.contribN=ctn;v.contribD=cD;v.contribR=cR;v.govD=gD;v.govR=gR;v.govDshare=(gD+gR)>0?gD/(gD+gR):null;
  v.orgs=(ORG[f]||[]).length;v.dcN=(DCC[f]||[]).length;v.dcMW=(DCC[f]||[]).reduce((a,s)=>a+(s.mw||0),0);const w=W[f]||{};v.rainPct=w.p;v.rain=w.r;v.wells=w.w;v.wellsNew=w.nw;});
const col=fn=>{const o={};F.forEach(f=>{const x=fn(f);if(x!=null&&!isNaN(x))o[f]=x;});return o;};
// ---- metrics for the map (one group at a time) ----
const M=(key,label,group,values,extra)=>Object.assign({key,label,group,values,skipZero:false},extra);const POL=['#1b4fa6','#5b8fd9','#b9cff0','#eceae4','#f3b3a6','#e05a4e','#a91b1b'],TURN=['#fde7c8','#f7c27f','#eea04a','#dd7a1f','#b85a0a','#7a3a03'];
const MARG_BINS=[-0.3,-0.1,-0.02,0.02,0.1,0.3],MARG_LBL=['Democratic by 30+ pts','Democratic by 10-30 pts','Democratic by 2-10 pts','within 2 pts','Republican by 2-10 pts','Republican by 10-30 pts','Republican by 30+ pts'],CHG_BINS=[-0.05,-0.02,-0.005,0.005,0.02,0.05],CHG_LBL=['5+ pts more Democratic','2-5 pts more Democratic','0.5-2 pts more Democratic','about the same','0.5-2 pts more Republican','2-5 pts more Republican','5+ pts more Republican'],TCHG_BINS=[-0.10,-0.05,-0.02,0.02,0.05,0.10],TCHG_LBL=['fell 10+ pts','fell 5-10 pts','fell 2-5 pts','about the same','rose 2-5 pts','rose 5-10 pts','rose 10+ pts'];
const METRICS=[
 M('turnout_2024','Turnout 2024','Turnout',col(f=>e(f,'turnout_2024')),{fmt:PCT,ramp:TURN,bins:[0.45,0.52,0.58,0.63,0.68],legendTitle:'Turnout, 2024 general election (top-race votes / registered voters)'}),
 M('turnout_2022','Turnout 2022 (midterm)','Turnout',col(f=>e(f,'turnout_2022')),{fmt:PCT,ramp:TURN,bins:[0.35,0.42,0.48,0.54,0.60],legendTitle:'Turnout, 2022 general election'}),
 M('turnout_change_2020_2024','Turnout change 2020 to 2024','Turnout',col(f=>e(f,'turnout_change_2020_2024')),{fmt:PTS,ramp:'diverging',bins:TCHG_BINS,binLabels:TCHG_LBL,legendTitle:'Turnout 2024 minus 2020 (points)'}),
 M('turnout_change_2018_2022','Turnout change 2018 to 2022 (midterms)','Turnout',col(f=>e(f,'turnout_change_2018_2022')),{fmt:PTS,ramp:'diverging',bins:TCHG_BINS,binLabels:TCHG_LBL,legendTitle:'Turnout 2022 minus 2018 (points)'}),
 M('primary_turnout_2018','Primary turnout 2018 (both parties)','Turnout',col(f=>e(f,'primary_turnout_2018')),{fmt:PCT,ramp:TURN,bins:[0.12,0.16,0.2,0.25,0.3],legendTitle:'2018 primary: D + R top-race votes / March registration'}),
 M('registration_growth_2020_2024','Registration growth 2020 to 2024','Registration',col(f=>e(f,'registration_growth_2020_2024')),{fmt:SPCT,ramp:'diverging',bins:[-0.05,-0.02,0,0.05,0.10,0.20],binLabels:['fell 5%+','fell 2-5%','fell up to 2%','grew up to 5%','grew 5-10%','grew 10-20%','grew 20%+'],legendTitle:'Registered voters, Nov. 2020 to Nov. 2024'}),
 M('reg_since_2022','Registration growth since the 2022 midterm','Registration',col(f=>V[f].regSince22),{fmt:SPCT,ramp:'diverging',bins:[-0.02,0,0.02,0.05,0.08,0.12],binLabels:['fell 2%+','fell up to 2%','grew up to 2%','grew 2-5%','grew 5-8%','grew 8-12%','grew 12%+'],legendTitle:'Registered voters, Nov. 2022 to Nov. 2024'}),
 M('registered_2026','Registered voters, March 2026','Registration',col(f=>e(f,'registered_march_2026')),{ramp:'purple',bins:[5000,15000,40000,100000,500000],legendTitle:'Registered voters, March 2026 (SOS, as of the March 3 primary)'}),
 M('reg_since_2024','Registration change Nov. 2024 to March 2026','Registration',col(f=>e(f,'registration_growth_2024_2026')),{fmt:SPCT,ramp:'diverging',bins:[-0.03,-0.01,0,0.01,0.03,0.06],binLabels:['fell 3%+','fell 1-3%','fell up to 1%','grew up to 1%','grew 1-3%','grew 3-6%','grew 6%+'],legendTitle:'Registered voters, Nov. 2024 to March 2026'}),
 M('registered_2024','Registered voters, Nov. 2024','Registration',col(f=>e(f,'registered_2024')),{ramp:'purple',bins:[5000,15000,40000,100000,500000],legendTitle:'Registered voters, November 2024'}),
 M('reg_vs_pop','Registration growth minus population growth','Registration',col(f=>V[f].regVsPop),{fmt:PTS,ramp:'diverging',bins:[-0.1,-0.05,-0.02,0.02,0.05,0.1],binLabels:['population far ahead (10+ pts)','population ahead 5-10','population ahead 2-5','about even','rolls ahead 2-5','rolls ahead 5-10','rolls far ahead (10+ pts)'],legendTitle:'Registration growth 2020-24 minus population growth 2020-25 (points)'}),
 M('pres_R_change_2020_2024','Republican presidential change 2020 to 2024','Election change',col(f=>e(f,'pres_R_change_2020_2024')),{fmt:PTS,ramp:POL,bins:CHG_BINS,binLabels:CHG_LBL,legendTitle:"Change in Trump's share, 2020 to 2024 (points)"}),
 M('pres_margin_2024','2024 President: Trump vs Harris margin','Election change',col(f=>e(f,'pres_margin_2024')),{fmt:v=>RMN(v,2024,'pres'),ramp:POL,bins:MARG_BINS,binLabels:['Harris by 30+ pts','Harris by 10-30 pts','Harris by 2-10 pts','within 2 pts','Trump by 2-10 pts','Trump by 10-30 pts','Trump by 30+ pts'],legendTitle:'President 2024: Trump share minus Harris share (points)'}),
 M('gov_margin_2022','2022 Governor: Abbott vs O\'Rourke margin','Election change',col(f=>e(f,'gov_margin_2022')),{fmt:v=>RMN(v,2022,'gov'),ramp:POL,bins:MARG_BINS,binLabels:["O'Rourke by 30+ pts","O'Rourke by 10-30 pts","O'Rourke by 2-10 pts",'within 2 pts','Abbott by 2-10 pts','Abbott by 10-30 pts','Abbott by 30+ pts'],legendTitle:'Governor 2022: Abbott share minus O\'Rourke share (points)'}),
 M('pres_R_2024','Republican presidential share 2024','Election change',col(f=>e(f,'pres_R_2024')),{fmt:PCT,ramp:'maroon',bins:[0.4,0.5,0.6,0.7,0.8],legendTitle:'Trump share, 2024'}),
 M('pres_D_2024','Democratic presidential share 2024','Election change',col(f=>e(f,'pres_D_2024')),{fmt:PCT,ramp:'blue',bins:[0.15,0.25,0.35,0.45,0.55],legendTitle:'Harris share, 2024'}),
 M('pres_margin_change_2016_2024','Change in presidential margin 2016 to 2024','Election change',col(f=>e(f,'pres_margin_change_2016_2024')),{fmt:PTS,ramp:POL,bins:[-0.1,-0.05,-0.02,0.02,0.05,0.1],binLabels:['10+ pts more Democratic','5-10 more Democratic','2-5 more Democratic','about the same','2-5 more Republican','5-10 more Republican','10+ pts more Republican'],legendTitle:'2024 margin minus 2016 margin (points)'}),
 M('gov_margin_change_2018_2022','Midterm swing: governor 2018 to 2022','Election change',col(f=>e(f,'gov_margin_change_2018_2022')),{fmt:PTS,ramp:POL,bins:CHG_BINS,binLabels:CHG_LBL,legendTitle:'Governor margin 2022 minus 2018 (points)'}),
 M('primary_D_share_2018','Democratic share of 2018 primary votes','Election change',col(f=>e(f,'primary_D_share_2018')),{fmt:PCT,ramp:'blue',bins:[0.15,0.25,0.35,0.5,0.65],legendTitle:'Democratic primary votes / all primary votes, 2018'}),
 M('downballot_money','Down-ballot money on the ballot (2026 YTD, TEC)','Fundraising',col(f=>V[f].money),{fmt:USDK,ramp:'orange',bins:[50000,150000,400000,1000000,2500000],binLabels:['under $50k','$50k-150k','$150k-400k','$400k-1M','$1M-2.5M','$2.5M+'],legendTitle:'Raised in 2026 by state-district candidates on the county\'s ballot',caption:'A district race counts in full for every county it touches.'}),
 M('contrib_R','Republican dollars from county donors (2026)','Fundraising',col(f=>V[f].contribR),{fmt:USDK,ramp:'maroon',bins:[10000,50000,200000,1000000,5000000],binLabels:['under $10k','$10k-50k','$50k-200k','$200k-1M','$1M-5M','$5M+'],legendTitle:'Itemized contributions from the county\'s donors to Republican candidates for state office, 2026 year to date (TEC)',caption:'Candidate accounts and linked committees; unitemized gifts cannot be placed.'}),
 M('contrib_D','Democratic dollars from county donors (2026)','Fundraising',col(f=>V[f].contribD),{fmt:USDK,ramp:'blue',bins:[10000,50000,200000,1000000,5000000],binLabels:['under $10k','$10k-50k','$50k-200k','$200k-1M','$1M-5M','$5M+'],legendTitle:'Itemized contributions from the county\'s donors to Democratic candidates for state office, 2026 year to date (TEC)',caption:'Candidate accounts and linked committees; unitemized gifts cannot be placed.'}),
 M('contrib_2026','All dollars from county donors (2026, state candidates)','Fundraising',col(f=>V[f].contrib),{fmt:USDK,ramp:'orange',bins:[10000,50000,200000,1000000,5000000],binLabels:['under $10k','$10k-50k','$50k-200k','$200k-1M','$1M-5M','$5M+'],legendTitle:'Itemized contributions from the county\'s donors to all 2026 state candidates, 2026 year to date (TEC)'}),
 M('cd_margin_2026','2026 congressional districts: 2024 presidential margin','Districts',(()=>{const o={};const yr=R[NEW]&&R[NEW].years[2024];if(yr)Object.keys(yr.d).forEach(n=>{const m=marg(NEW,2024,'pres',n);if(m!=null)o[n]=m;});return o;})(),{plan:NEW,fmt:RM,ramp:POL,bins:MARG_BINS,binLabels:MARG_LBL,legendTitle:'2026 map (PLANC2333): 2024 presidential vote re-tabulated by district, Republican minus Democratic (points)',caption:'Each shape is a district of the 2026 map; county lines show through. Click a district for its history.'}),
 M('cd_margin_2024','2024 congressional districts: 2024 presidential margin','Districts',(()=>{const o={};const yr=R[OLD]&&R[OLD].years[2024];if(yr)Object.keys(yr.d).forEach(n=>{const m=marg(OLD,2024,'pres',n);if(m!=null)o[n]=m;});return o;})(),{plan:OLD,fmt:RM,ramp:POL,bins:MARG_BINS,binLabels:MARG_LBL,legendTitle:'2024 map (PLANC2193): 2024 presidential vote by district, Republican minus Democratic (points)'}),
 M('cd_change_share','Residents with a new congressional district number (2026 map)','Districts',col(f=>X.changed[f]||0),{fmt:PCT0,ramp:'purple',bins:[0.001,0.25,0.5,0.75,0.999],binLabels:['none','under 25%','25-50%','50-75%','75-99%','all'],legendTitle:'Share of 2020 residents whose congressional district number changed from the 2024 map (PLANC2193) to the 2026 map (PLANC2333)'}),
 M('orgs_n','Community organizations listed','Community',col(f=>V[f].orgs),{ramp:'green',bins:[1,3,6,12,25],binLabels:['none','1-2','3-5','6-11','12-24','25+'],legendTitle:'Organizations listed for the county, all sectors'}),
 M('pop_change','Population change 2020 to 2025','Population',col(f=>d(f,'Pop. change 2020-2025 (%)')),{fmt:SPCT,ramp:'diverging',bins:[-0.05,-0.02,0,0.03,0.08,0.15],binLabels:['lost 5%+','lost 2-5%','lost up to 2%','grew up to 3%','grew 3-8%','grew 8-15%','grew 15%+'],legendTitle:'Population change, April 2020 to July 2025 (TDC preliminary)'}),
 M('pop_2025','Population 2025','Population',col(f=>d(f,'Population, July 1 2025 (TDC prelim.)')),{ramp:'purple',bins:[5000,15000,50000,150000,500000],legendTitle:'Population, July 2025'}),
 M('hispanic','Hispanic share','Demographics',col(f=>d(f,'Hispanic (%)')),{fmt:PCT,ramp:'teal',bins:[0.1,0.2,0.3,0.5,0.7,0.9],legendTitle:'Hispanic or Latino share (ACS 2020-24)'}),
 M('white','White (non-Hispanic) share','Demographics',col(f=>d(f,'Non-Hispanic White (%)')),{fmt:PCT,ramp:'purple',bins:[0.2,0.4,0.6,0.75,0.85],legendTitle:'Non-Hispanic White share'}),
 M('black','Black (non-Hispanic) share','Demographics',col(f=>d(f,'Non-Hispanic Black (%)')),{fmt:PCT,ramp:'green',bins:[0.02,0.05,0.1,0.15,0.25],legendTitle:'Non-Hispanic Black share'}),
 M('asian','Asian (non-Hispanic) share','Demographics',col(f=>d(f,'Non-Hispanic Asian (%)')),{fmt:PCT,ramp:'blue',bins:[0.01,0.02,0.05,0.1,0.2],legendTitle:'Non-Hispanic Asian share'}),
 M('income','Median household income','Demographics',col(f=>d(f,'Median household income ($)')),{fmt:USD,ramp:'orange',bins:[45000,55000,65000,80000,100000],legendTitle:'Median household income (ACS 2020-24)'}),
 M('poverty','Poverty rate','Demographics',col(f=>d(f,'Poverty rate (%)')),{fmt:PCT,ramp:'maroon',bins:[0.1,0.14,0.18,0.22,0.28],legendTitle:'Share below the poverty line'}),
 M('bach',"Bachelor's degree or higher",'Demographics',col(f=>d(f,"Bachelor's degree or higher, 25+ (%)")),{fmt:PCT,ramp:'green',bins:[0.12,0.16,0.2,0.28,0.4],legendTitle:"Adults 25+ with a bachelor's degree"}),
 M('age','Median age','Demographics',col(f=>d(f,'Median age')),{fmt:v=>v.toFixed(1),ramp:'blue',bins:[32,36,40,44,48],legendTitle:'Median age'}),
 M('aq_main','Main aquifer under the county','Water',col(f=>{const m=((AQ[f]||{}).aq||[]).find(x=>x[1]==='major');return m?m[0]:null;}),{cat:true,categories:(()=>{const o={};F.forEach(f=>{const m=((AQ[f]||{}).aq||[]).find(x=>x[1]==='major');if(m&&!o[m[0]])o[m[0]]={label:m[0],color:(CM.aqColor&&CM.aqColor(m[0]))||'#b9b2a6'};});return o;})(),noneLabel:'No major aquifer',legendTitle:'Main aquifer under each county (largest share of county area, TWDB major aquifers)',caption:'Turn on the Aquifers layer to see the outlines themselves.'}),
 M('rain_pct','Rain, last 12 months vs. usual','Water',col(f=>V[f].rainPct),{fmt:v=>v+'% of usual',ramp:'diverging',bins:[50,70,90,110,130,150],binLabels:['under 50% of usual','50-70%','70-90%','about usual (90-110%)','110-130%','130-150%','over 150%'],legendTitle:'Rain in the last twelve months as a share of the county\'s usual year'}),
 M('rain_avg','Average yearly rainfall','Water',col(f=>V[f].rain),{unit:'in/yr',ramp:'blue',bins:[16,22,28,36,46],legendTitle:'Average rainfall, inches per year (1991-2020)'}),
 M('wells_new','Wells drilled since 2020','Water',col(f=>V[f].wellsNew),{ramp:'teal',bins:[50,150,400,1000,2500],legendTitle:'Water-supply wells drilled since January 2020 (TWDB driller reports)'}),
 M('wells_all','Wells on record','Water',col(f=>V[f].wells),{ramp:'teal',bins:[100,300,800,2000,5000],legendTitle:'Wells on record (TWDB groundwater database)'}),
 M('dc_n','Data center projects','Data centers',col(f=>V[f].dcN),{ramp:'orange',bins:[1,2,4,8,20],binLabels:['none','1','2-3','4-7','8-19','20+'],legendTitle:'Announced, under-construction or operating data center projects'}),
 M('dc_mw','Announced data center power (MW)','Data centers',col(f=>V[f].dcMW),{unit:'MW',ramp:'orange',bins:[50,200,500,1000,3000],legendTitle:'Announced power, megawatts (where reported)'})];
const GROUPS=[['Turnout','turnout_2024'],['Registration','registration_growth_2020_2024'],['Election change','pres_R_change_2020_2024'],['Fundraising','contrib_R'],['Districts','cd_margin_2026'],['Population','pop_change'],['Demographics','hispanic'],['Water','rain_pct'],['Data centers','dc_n']];
const TEXAS={registered_2026:S.registered_march_2026,reg_since_2024:S.registration_growth_2024_2026,turnout_2024:S.turnout_2024,turnout_2022:S.turnout_2022,turnout_change_2020_2024:S.turnout_change_2020_2024,turnout_change_2018_2022:S.turnout_change_2018_2022,primary_turnout_2018:S.primary_turnout_2018,registration_growth_2020_2024:S.registration_growth_2020_2024,reg_since_2022:S.registered_2024/S.registered_2022-1,registered_2024:S.registered_2024,reg_vs_pop:S.registration_growth_2020_2024-(TXD['Pop. change 2020-2025 (%)']||0),pres_R_change_2020_2024:S.pres_R_change_2020_2024,pres_margin_2024:S.pres_margin_2024,pres_R_2024:S.pres_R_2024,pres_D_2024:S.pres_D_2024,pres_margin_change_2016_2024:S.pres_margin_change_2016_2024,gov_margin_change_2018_2022:S.gov_margin_change_2018_2022,primary_D_share_2018:S.primary_D_share_2018,pop_change:TXD['Pop. change 2020-2025 (%)'],pop_2025:TXD['Population, July 1 2025 (TDC prelim.)'],hispanic:TXD['Hispanic (%)'],white:TXD['Non-Hispanic White (%)'],black:TXD['Non-Hispanic Black (%)'],asian:TXD['Non-Hispanic Asian (%)'],income:TXD['Median household income ($)'],poverty:TXD['Poverty rate (%)'],bach:TXD["Bachelor's degree or higher, 25+ (%)"],age:TXD['Median age'],dc_n:Object.values(DCC).reduce((a,l)=>a+l.length,0),dc_mw:Object.values(DCC).reduce((a,l)=>a+l.reduce((x,s)=>x+(s.mw||0),0),0)};
// ---- state ----
const ST={f:'',tab:'overview',cmp:[],pair:'2020-2024',dmap:NEW,place:'',lock:false,lastBase:'',lastPlan:'PLANC2333'};try{const c=JSON.parse(localStorage.getItem('txdd_compare')||'[]');if(Array.isArray(c))ST.cmp=c.filter(x=>DM[x]).slice(0,3);}catch(x){}
const TABS=[['overview','Overview','Who lives here?'],['elections','Elections','How politically active is the county, and how has it voted?'],['ballot','Ballot','What is on the 2026 ballot, and who are the party contacts?'],['money','Money','Where is campaign money flowing?'],['districts','Districts','What changed because of redistricting?'],['community','Community','Which organizations are present, and who should I talk to?'],['water','Water','What water and aquifer context matters?'],['dc','Data Centers','What data-center activity is there?']];
const side=$('side');
function setHash(){const h=[];if(ST.f)h.push('county='+ST.f);if(ST.tab!=='overview')h.push('tab='+ST.tab);if(ST.cmp.length)h.push('compare='+ST.cmp.join(','));const m=CM.state.base;if(m&&m!=='pres_R_change_2020_2024')h.push('color='+m);const pl=CM.activePlan();if(pl)h.push('lines='+pl);const L=['rivers','basins','aquifers'].filter(k=>CM.state[k]);if(CM.state.pins&&!(CM.state.base||'').startsWith('dc_'))L.push('dots');if(L.length)h.push('layers='+L.join(','));if(ST.lock)h.push('lock=1');CM.setHash(h.join('&'));}
// ---- header tabs ----
function renderTabs(){const html=TABS.map(([k,l,q])=>`<button type="button" data-tab="${k}" title="${esc(q)}"${ST.tab===k?' class="on"':''}>${l}</button>`).join('');$('tabs').innerHTML=html;$('tabs2').innerHTML=html;}
const TABSYM={overview:['pop_change','pop_2025','registered_2026','hispanic','income','poverty','white','black','asian','bach','age'],elections:['pres_margin_2024','gov_margin_2022','pres_R_change_2020_2024','turnout_2024','turnout_change_2020_2024','turnout_change_2018_2022','reg_since_2024','pres_R_2024','pres_D_2024','registration_growth_2020_2024','pres_margin_change_2016_2024','gov_margin_change_2018_2022','turnout_2022','primary_turnout_2018','primary_D_share_2018','reg_since_2022','reg_vs_pop'],ballot:['contrib_R','contrib_D','contrib_2026','downballot_money'],money:['contrib_R','contrib_D','contrib_2026','downballot_money'],districts:['cd_margin_2026','cd_margin_2024','cd_change_share'],community:['orgs_n'],water:['rain_pct','rain_avg','wells_new','wells_all','aq_main'],dc:['dc_n','dc_mw']};
const TABDEF={overview:'pop_change',elections:'pres_margin_2024',ballot:'contrib_R',money:'contrib_R',districts:'cd_margin_2026',community:'orgs_n',water:'rain_pct',dc:'dc_n'};
function followTab(){if(ST.lock)return;const d=TABDEF[ST.tab];if(d&&CM.metric(d)&&CM.state.base!==d){CM.setBase(d);ST.lastBase=d;}if(ST.tab==='dc'&&!CM.state.pins)CM.setLayers({pins:true});}
document.addEventListener('click',ev=>{const b=ev.target.closest('.tabs button');if(!b)return;ST.tab=b.dataset.tab;followTab();renderTabs();renderRibbon();renderPanel();setHash();CM.closeAside();});
// ---- search: counties + places ----
const ITEMS=Object.keys(cname).map(f=>({label:cname[f]+' County',sub:(RG[f]||{}).Region||'',f,kind:'county',key:cname[f].toLowerCase()})).concat(PL.map(p=>({label:p[0],sub:p[4]==='CDP'?'community in '+cname[p[1]]+' County':p[4]+' in '+cname[p[1]]+' County',f:p[1],kind:'place',key:p[0].toLowerCase()})));
const q=$('q'),sg=$('sg');let sgi=0,sgItems=[];
function suggest(v){v=v.trim().toLowerCase();if(!v){sg.style.display='none';return;}sgItems=ITEMS.filter(it=>it.key.startsWith(v)||it.key.split(/[\s-]/).some(w=>w.startsWith(v))).sort((a,b)=>(a.kind==='county'?0:1)-(b.kind==='county'?0:1)||a.label.localeCompare(b.label)).slice(0,12);sgi=0;
  sg.innerHTML=sgItems.map((it,i)=>`<div data-i="${i}"${i===sgi?' class="on"':''}><span>${esc(it.label)}</span><small>${esc(it.sub)}</small></div>`).join('')||'<div><small>No county or place matches.</small></div>';sg.style.display='block';}
function pick(it){sg.style.display='none';q.value='';if(!it)return;ST.place=it.kind==='place'?it.label:'';showCounty(it.f);CM.closeAside();}
q.addEventListener('input',()=>suggest(q.value));q.addEventListener('focus',()=>{if(q.value)suggest(q.value);});
q.addEventListener('keydown',ev=>{if(ev.key==='ArrowDown'){sgi=Math.min(sgi+1,sgItems.length-1);suggest(q.value);ev.preventDefault();}else if(ev.key==='ArrowUp'){sgi=Math.max(sgi-1,0);suggest(q.value);ev.preventDefault();}else if(ev.key==='Enter'){pick(sgItems[sgi]);}else if(ev.key==='Escape'){sg.style.display='none';}});
sg.addEventListener('mousedown',ev=>{const dv=ev.target.closest('div[data-i]');if(dv){ev.preventDefault();pick(sgItems[+dv.dataset.i]);}});
document.addEventListener('click',ev=>{if(!ev.target.closest('.ccsearch'))sg.style.display='none';});
// ---- ribbon: the tools for the active tab (what colors the counties, tab-specific choices, actions) ----
const PLANS=[['PLANC2333','U.S. Congress, 2026 map'],['PLANC2193','U.S. Congress, 2024 map'],['PLANH2316','Texas House'],['PLANS2168','Texas Senate'],['PLANE2106','State Board of Education']];
function renderRibbon(){const t=ST.tab,cur=CM.state.base,cm=CM.metric(cur);const syms=(TABSYM[t]||[]).map(k=>CM.metric(k)).filter(Boolean);const inTab=syms.some(m=>m.key===cur);
  const g=(items,cap)=>`<div class="rg"><div class="rgi">${items}</div><div class="rgc">${cap}</div></div>`;
  const first=syms.slice(0,6),more=syms.slice(6);const curInMore=more.some(m=>m.key===cur);
  let h=g(first.map(m=>`<button type="button" data-sym="${m.key}" title="${esc(m.legendTitle||m.label)}"${m.key===cur?' class="on"':''}>${esc(m.label)}</button>`).join('')+(more.length?`<select data-more aria-label="More measures"${curInMore?' class="on"':''}><option value="">${curInMore?esc(CM.metric(cur).label):'More measures…'}</option>${more.map(m=>`<option value="${m.key}"${m.key===cur?' selected':''}>${esc(m.label)}</option>`).join('')}</select>`:'')+`<button type="button" data-sym="" title="County outlines only"${!cur?' class="on"':''}>No color</button>`,'Color the counties by');
  if(cm&&!inTab)h+=g(`<span class="rbnote">Map shows <b>${esc(cm.label)}</b>${ST.lock?' (locked)':''}</span>`,'From another tab');
  if(t==='elections'&&ST.f)h+=g(PAIRS.map(p=>`<button type="button" data-pair="${p[0]}"${ST.pair===p[0]?' class="on"':''}>${p[1]}</button>`).join(''),'Compare two elections in the panel');
  if(t==='districts')h+=g(`<button type="button" data-dmap="PLANC2193"${ST.dmap===OLD?' class="on"':''}>2024 map</button><button type="button" data-dmap="PLANC2333"${ST.dmap===NEW?' class="on"':''}>2026 map</button>`,'Which map the panel describes');
  h+=g(`<button type="button" data-act="cmp"${!ST.f||ST.cmp.includes(ST.f)||ST.cmp.length>=3?' disabled':''} title="Put this county in the comparison table at the bottom">+ Add to compare</button><button type="button" class="primary" data-act="brief"${!ST.f?' disabled':''} title="Open a one-page brief for this county">Prepare roundtable</button>`,ST.f?esc(cname[ST.f])+' County':'Pick a county');
  h+=g(`<button type="button" data-tool="lock"${ST.lock?' class="on"':''} title="${ST.lock?'The map keeps its coloring when you change tabs. Click to let it follow the tab again.':'The map recolors to match each tab. Click to keep the current coloring.'}">${ST.lock?'Coloring locked':'Coloring follows the tab'}</button><button type="button" data-tool="fit" title="Zoom back out to the whole state">Whole state</button>`,'Map');
  $('ribbon').innerHTML=h;}
$('ribbon').addEventListener('change',ev=>{const sel=ev.target.closest('[data-more]');if(sel&&sel.value){CM.setBase(sel.value);ST.lastBase=sel.value;renderRibbon();setHash();}});
$('ribbon').addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b||b.disabled)return;
  if(b.dataset.sym!==undefined){CM.setBase(b.dataset.sym);ST.lastBase=b.dataset.sym;renderRibbon();setHash();return;}
  if(b.dataset.tool==='lock'){ST.lock=!ST.lock;renderRibbon();setHash();return;}
  if(b.dataset.tool==='fit'){CM.fit();return;}});
// ---- contents pane: every layer on the map with its symbology, straight from the engine's legend ----
function legendSections(){const body=$('legend').querySelector('.lgbody');const out=[];let cur=null;if(!body)return out;[...body.children].forEach(el=>{if(el.tagName==='B'){cur={title:el.textContent,rows:[]};out.push(cur);}else if(cur)cur.rows.push(el.outerHTML);});return out;}
function renderContents(){const m=CM.metric(CM.state.base);const secs=legendSections();const KNOWN=['Rivers & lakes','River basins','Major aquifers','Minor aquifers','District lines','Data center projects'];const find=t=>secs.find(x=>x.title===t);const cl=secs.find(x=>!KNOWN.includes(x.title));const pl=CM.activePlan();const forced=m&&m.plan;
  const layer=(id,on,label,sub,rows,extra='',dis=false)=>`<div class="lyr${on?' on':' off'}"><label><input type="checkbox" data-lyr="${id}"${on?' checked':''}${dis?' disabled':''}> <b>${label}</b></label>${extra}${sub?`<div class="lsub">${sub}</div>`:''}${on&&rows&&rows.length?`<div class="lrows">${rows.join('')}</div>`:''}</div>`;
  $('contents').innerHTML=`<div class="ph"><span>Contents</span><button type="button" class="collapse" data-collapse="contents" title="Collapse this pane">«</button></div>`
    +layer('counties',!!m,m&&m.plan?'Districts':'Counties',m?'colored by '+esc(m.label):'outlines only; pick a measure in the ribbon above',m&&cl?cl.rows:[])
    +layer('lines',!!pl,'District lines','',find('District lines')?find('District lines').rows:(forced?[`<div class="r"><i class="distsw"></i>${esc((CM.plan(pl)||{}).label||'')}</div>`]:[]),`<select data-plan-sel${forced?' disabled':''} aria-label="Which district lines">${PLANS.map(([p,l])=>`<option value="${p}"${(pl||ST.lastPlan)===p?' selected':''}>${l}</option>`).join('')}</select>`,!!forced)
    +layer('aquifers',CM.state.aquifers,'Aquifers','TWDB major aquifers',find('Major aquifers')?find('Major aquifers').rows:[])
    +layer('rivers',CM.state.rivers,'Rivers & lakes','',find('Rivers & lakes')?find('Rivers & lakes').rows:[])
    +layer('basins',CM.state.basins,'River basins','',find('River basins')?find('River basins').rows:[])
    +layer('pins',CM.state.pins,'Data center projects','',find('Data center projects')?find('Data center projects').rows:[]);}
$('contents').addEventListener('change',ev=>{const c=ev.target.closest('[data-lyr]');if(c){const k=c.dataset.lyr;
    if(k==='counties'){CM.setBase(c.checked?(ST.lastBase||TABDEF[ST.tab]||'pop_change'):'');renderRibbon();}
    else if(k==='lines'){const sel=$('contents').querySelector('[data-plan-sel]');CM.setPlan(c.checked?(sel?sel.value:ST.lastPlan):'');}
    else{const o={};o[k]=c.checked;CM.setLayers(o);}
    setHash();return;}
  const sel=ev.target.closest('[data-plan-sel]');if(sel){ST.lastPlan=sel.value;if(CM.activePlan())CM.setPlan(sel.value);setHash();}});
document.addEventListener('click',ev=>{const b=ev.target.closest('[data-collapse]');if(!b)return;const app=document.querySelector('.app');if(b.dataset.collapse==='contents'){if(window.innerWidth<=900)$('contents').classList.remove('open');else app.classList.toggle('no-contents');}else{if(window.innerWidth<=900)document.querySelector('aside').classList.remove('open');else app.classList.toggle('no-side');}});
$('layersbtn').onclick=()=>{$('contents').classList.toggle('open');document.querySelector('aside').classList.remove('open');};
// ---- status bar: county under the cursor, a scale bar, statewide figures ----
function updateScale(v){v=v||CM.view();const svg=$('map');if(!svg||!v)return;const ratio=Math.min(svg.clientWidth/v.W,svg.clientHeight/v.H);const pxPerKm=ratio*v.sc/1.1119;let km=[2,5,10,25,50,100,200,500].find(k=>k*pxPerKm>=70)||500;const w=Math.round(km*pxPerKm);const denom=1e6/(pxPerKm*0.26458);const r=Math.pow(10,Math.floor(Math.log10(denom))-1);$('sb-scale').innerHTML=`<i style="width:${w}px"></i>${km} km · 1:${num(Math.round(denom/r)*r)}`;}
$('map').addEventListener('pointermove',e=>{const [lon,lat]=CM.cursorLonLat(e);const f=CM.countyAt(lon,lat);const m=CM.metric(CM.state.base);$('sb-cur').textContent=(f?cname[f]+' County'+(m&&!m.plan?' · '+m.label+': '+CM.fmtValue(m.key,f):''):'')+(f?' · ':'')+Math.abs(lat).toFixed(3)+'°N '+Math.abs(lon).toFixed(3)+'°W';});
$('map').addEventListener('pointerleave',()=>{$('sb-cur').textContent=ST.f?cname[ST.f]+' County':'Move over the map to read a county';});
// ---- compare tray ----
function saveCmp(){try{localStorage.setItem('txdd_compare',JSON.stringify(ST.cmp));}catch(x){}}
const ROWS=[['Registered voters, March 2026',f=>e(f,'registered_march_2026'),num],['Registration change Nov. 2024 to March 2026',f=>e(f,'registration_growth_2024_2026'),SPCT],['Registered voters, Nov. 2024',f=>e(f,'registered_2024'),num],['Registration growth 2020 to 2024',f=>e(f,'registration_growth_2020_2024'),SPCT],['Turnout 2024',f=>e(f,'turnout_2024'),PCT],['Turnout 2022',f=>e(f,'turnout_2022'),PCT],['Turnout change 2018 to 2022',f=>e(f,'turnout_change_2018_2022'),PTS],['2024 Republican presidential share',f=>e(f,'pres_R_2024'),PCT],['2024 President: margin (Trump vs Harris)',f=>e(f,'pres_margin_2024'),v=>RMN(v,2024,'pres')],['2022 Governor: margin (Abbott vs O\'Rourke)',f=>e(f,'gov_margin_2022'),v=>RMN(v,2022,'gov')],['Republican change 2020 to 2024',f=>e(f,'pres_R_change_2020_2024'),PTS],['Population 2025',f=>d(f,'Population, July 1 2025 (TDC prelim.)'),num],['Population growth 2020 to 2025',f=>d(f,'Pop. change 2020-2025 (%)'),SPCT],['Hispanic share',f=>d(f,'Hispanic (%)'),PCT],['Median household income',f=>d(f,'Median household income ($)'),USD],['Republican dollars from county donors (2026)',f=>f==='48'?sumBy(x=>V[x].contribR):V[f].contribR,USDK],['Democratic dollars from county donors (2026)',f=>f==='48'?sumBy(x=>V[x].contribD):V[f].contribD,USDK],['Down-ballot money on the ballot (2026)',f=>f==='48'?null:V[f].money,USDK],['Community organizations listed',f=>f==='48'?(O.orgs||[]).length:V[f].orgs,num],['Data center projects',f=>f==='48'?TEXAS.dc_n:V[f].dcN,num],['Rain, last 12 months vs. usual',f=>f==='48'?null:V[f].rainPct,v=>v+'%'],['2026 congressional district(s)',f=>f==='48'?null:((X.counties[f]||{})[NEW]||[]).map(([n])=>'CD '+n).join(', '),v=>v]];
function renderTray(){const t=$('tray');const list=ST.cmp;const cols=list.map(f=>esc(cname[f])).concat(['Texas']);
  t.innerHTML=`<div class="th" id="tray-h"><b>Compare</b>${list.map(f=>`<span class="chip">${esc(cname[f])}<i data-rm="${f}" title="Remove">✕</i></span>`).join('')}<span class="hint">${list.length?'':'Add up to three counties from a county page.'}${ST.f&&!list.includes(ST.f)&&list.length<3?` <button type="button" data-add="${ST.f}" style="font:600 12px IBM Plex Sans,sans-serif;padding:3px 8px;border-radius:999px;border:1px solid var(--rule);background:var(--paper2);cursor:pointer">+ Add ${esc(cname[ST.f])}</button>`:''}</span><span class="chev">${t.classList.contains('closed')?'▴':'▾'}</span></div>
    <div class="tbody">${list.length?`<table><tr><th>Metric</th>${cols.map(c=>`<th>${c}</th>`).join('')}</tr>${ROWS.map(([lab,fn,fmt])=>`<tr><td>${lab}</td>${list.concat(['48']).map(f=>{const v=fn(f);return `<td>${v==null||v===''||(typeof v==='number'&&isNaN(v))?'—':fmt(v)}</td>`;}).join('')}</tr>`).join('')}</table>`:'<div class="ccnote">Open a county and press "Add to compare"; two or three counties appear here side by side, always next to Texas.</div>'}</div>`;}
$('tray').addEventListener('click',ev=>{const rm=ev.target.closest('[data-rm]');if(rm){ST.cmp=ST.cmp.filter(f=>f!==rm.dataset.rm);saveCmp();renderTray();renderPanel();setHash();return;}
  const ad=ev.target.closest('[data-add]');if(ad){addCompare(ad.dataset.add);return;}
  if(ev.target.closest('#tray-h')){$('tray').classList.toggle('closed');renderTray();}});
function addCompare(f){if(!ST.cmp.includes(f)&&ST.cmp.length<3){ST.cmp.push(f);saveCmp();}$('tray').classList.remove('closed');renderTray();renderPanel();setHash();}
// keep the map legend just above the compare tray: main gets --tray-h = the tray's current height (see tx_deep_dive.css)
// ---- statements: What to know ----
function know(f){const c=E.counties[f]||{},v=V[f]||{};const out=[];const st=(t,ev)=>out.push({t,ev});
  if(c.registered_march_2026!=null&&c.registered_2024)st(`Voter registration ${c.registered_march_2026>=c.registered_2024?'grew':'fell'} since the 2024 election`,[['Nov. 2022',num(c.registered_2022)],['Nov. 2024',num(c.registered_2024)],['March 2026',num(c.registered_march_2026),1],['Change since Nov. 2024',SPCT(c.registration_growth_2024_2026),1],['Texas',SPCT(S.registration_growth_2024_2026)],['On the suspense list',num(c.suspense_march_2026)+' ('+PCT(c.suspense_march_2026/c.registered_march_2026)+')']]);
  else if(v.regSince22!=null)st(`Voter registration ${v.regSince22>=0?'increased':'decreased'} since the 2022 midterm`,[['Nov. 2022',num(c.registered_2022)],['Nov. 2024',num(c.registered_2024)],['Change',SPCT(v.regSince22),1],['Texas',SPCT(TEXAS.reg_since_2022)]]);
  if(c.turnout_change_2018_2022!=null)st(`Midterm turnout ${c.turnout_change_2018_2022<0?'fell':'rose'}`,[['2018',PCT(c.turnout_2018)],['2022',PCT(c.turnout_2022)],['Change',PTS(c.turnout_change_2018_2022),1],['Texas',PTS(S.turnout_change_2018_2022)]]);
  if(c.turnout_change_2020_2024!=null)st(`Presidential turnout ${c.turnout_change_2020_2024<0?'fell':'rose'} from 2020 to 2024`,[['2020',PCT(c.turnout_2020)],['2024',PCT(c.turnout_2024)],['Change',PTS(c.turnout_change_2020_2024),1],['Texas',PTS(S.turnout_change_2020_2024)]]);
  if(c.pres_R_change_2020_2024!=null)st(`Republican presidential vote share ${c.pres_R_change_2020_2024>=0?'increased':'decreased'} from 2020 to 2024`,[['2020',PCT(c.pres_R_2020)],['2024',PCT(c.pres_R_2024)],['Change',PTS(c.pres_R_change_2020_2024),1],['Texas',PTS(S.pres_R_change_2020_2024)]]);
  if(c.pres_margin_2024!=null)st(`${c.pres_margin_2024>0?'Republicans':'Democrats'} won the 2024 presidential vote here`,[['Republican',PCT(c.pres_R_2024)+' ('+num(c.pres_R_votes_2024)+')'],['Democratic',PCT(c.pres_D_2024)+' ('+num(c.pres_D_votes_2024)+')'],['Margin',RMN(c.pres_margin_2024,2024,'pres'),1],['Texas',RMN(S.pres_margin_2024,2024,'pres')]]);
  if(c.gov_margin_2022!=null)st(`${c.gov_margin_2022>0?'Abbott':"O'Rourke"} won the 2022 governor's race here`,[['Abbott',PCT(c.gov_R_2022)+(c.gov_R_votes_2022!=null?' ('+num(c.gov_R_votes_2022)+')':'')],["O'Rourke",PCT(c.gov_D_2022)+(c.gov_D_votes_2022!=null?' ('+num(c.gov_D_votes_2022)+')':'')],['Margin',RMN(c.gov_margin_2022,2022,'gov'),1],['Texas',RMN(S.gov_margin_2022,2022,'gov')]]);
  const nw=((X.counties[f]||{})[NEW]||[]).map(([n])=>'CD '+n).join(' + '),od=((X.counties[f]||{})[OLD]||[]).map(([n])=>'CD '+n).join(' + ');
  st(v.cdChg>=0.999?"The county's congressional district changes in 2026":v.cdChg>0?"The county's congressional geography changes in 2026":"The county's congressional district number does not change in 2026",[['2024 map',od||'—'],['2026 map',nw||'—'],['Residents with a new district number',PCT0(v.cdChg),1]].concat(v.leanChg!=null?[['District lean, 2024 presidential vote',RM(v.leanOld)+' → '+RM(v.leanNew)]]:[]));
  if(v.moneyN)st(`${v.moneyN===1?'One down-ballot candidate has':'Several down-ballot races have'} active fundraising`,[['Candidates reporting',num(v.moneyN)],['Raised in 2026',USDK(v.money),1],['Best-funded race',topRace(f)]]);else st('No state-district race here has reported money yet',[['Note','TEC reports cover state offices; federal and county offices file elsewhere']]);
  const cats=CATS.filter(ct=>(ORG[f]||[]).some(o=>o.cat===ct));if(cats.length)st(`${cats.length>2?cats.slice(0,2).join(', ')+' and other sectors':cats.join(' and ')} ${cats.length===1?'has':'have'} established local organizations`,[['Organizations listed',num(v.orgs),1],['Sectors',cats.map(ct=>ct+' ('+(ORG[f]||[]).filter(o=>o.cat===ct).length+')').join(', ')]]);else st('No community organizations collected here yet',[['Note','statewide directories had no entry; add local groups where a roundtable is planned']]);
  const infra=[];if(v.rainPct!=null&&(v.rainPct<80||v.rainPct>120))infra.push(v.rainPct<80?'a dry year':'a wet year');if(v.dcN)infra.push('data-center development');
  st(infra.length?`The county has ${infra.join(' and ')} to watch`:'No major water or data-center pressure flagged',[['Rain, last 12 months',v.rainPct!=null?v.rainPct+'% of usual':'—',v.rainPct!=null&&(v.rainPct<80||v.rainPct>120)?1:0],['Wells drilled since 2020',v.wellsNew!=null?num(v.wellsNew):'—'],['Data center projects',num(v.dcN)+(v.dcMW?' ('+num(v.dcMW)+' MW announced)':''),v.dcN?1:0],['Aquifers',aqList(f)]]);
  return out;}
function topRace(f){const bc=B.counties[f];if(!bc)return '—';const t={};bc.cands.forEach(i=>{const cd=B.cands[i],o=B.offices[cd[1]];if(DOWN.has(o[1])&&raceTot[o[0]]!=null)t[o[0]]=raceTot[o[0]];});const top=Object.entries(t).sort((a,b)=>b[1]-a[1])[0];return top?title(top[0])+' ('+USDK(top[1])+')':'—';}
const title=s=>String(s).toLowerCase().replace(/\b\w/g,ch=>ch.toUpperCase()).replace(/\bOf\b/g,'of').replace(/\bThe\b/g,'the');
const aqList=f=>((AQ[f]||{}).aq||[]).slice(0,3).map(a=>a[0]+' ('+PCT0(a[2])+(a[1]==='minor'?', minor':'')+')').join('; ')||'none mapped';
const knowHTML=f=>knowBlock(know(f));
function knowBlock(list){return `<div class="know"><div class="kt">What to know</div>${list.map(s=>`<div class="st"><b>${esc(s.t)}</b><div class="ev">${s.ev.map(([k,v,hi])=>`<span${hi?' class="chg"':''}>${esc(k)}: ${esc(String(v))}</span>`).join('')}</div></div>`).join('')}</div>`;}
// ---- tables with county, compare counties and Texas ----
function cmpTable(f,rows){const cols=[f].concat(ST.cmp.filter(x=>x!==f)).concat(['48']);
  return `<table class="cmp"><tr><th>Measure</th>${cols.map(x=>`<th>${x==='48'?'Texas':esc(cname[x])}</th>`).join('')}</tr>${rows.map(([lab,fn,fmt])=>`<tr><td>${lab}</td>${cols.map((x,i)=>{const v=fn(x);return `<td${i===0?' class="me"':''}>${v==null||v===''||(typeof v==='number'&&isNaN(v))?'—':fmt(v)}</td>`;}).join('')}</tr>`).join('')}</table>`;}
const H=t=>`<div class="h3">${t}</div>`;
// ---- tabs ----
const TOPIND=['Agriculture, forestry, fishing, hunting & mining (%)','Construction (%)','Manufacturing (%)','Wholesale trade (%)','Retail trade (%)','Transportation, warehousing & utilities (%)','Information (%)','Finance, insurance & real estate (%)','Professional, scientific, management & administrative services (%)','Educational services & health care (%)','Arts, entertainment, recreation, accommodation & food services (%)','Other services (%)','Public administration (%)'];
const topInd=(f,n)=>TOPIND.map(k=>[k.replace(' (%)',''),d(f,k)]).filter(x=>x[1]!=null).sort((a,b)=>b[1]-a[1]).slice(0,n);
function tabOverview(f){return H('Who lives here?')+cmpTable(f,[['Population, July 2025',x=>d(x,'Population, July 1 2025 (TDC prelim.)'),num],['Population change since 2020',x=>d(x,'Pop. change 2020-2025 (%)'),SPCT],['Adults 18 and over',x=>d(x,'Adults 18+ (ACS 2020-24)'),num],['Registered voters, March 2026',x=>e(x,'registered_march_2026'),num],['Change in registration, Nov. 2024 to March 2026',x=>e(x,'registration_growth_2024_2026'),SPCT],['On the suspense list, March 2026',x=>e(x,'suspense_march_2026'),num],['Registered voters, Nov. 2024',x=>e(x,'registered_2024'),num],['Registered as a share of adults (March 2026)',x=>x==='48'?S.registered_march_2026/TXD['Adults 18+ (ACS 2020-24)']:V[x].regOfAdults,PCT0],['Turnout 2024',x=>e(x,'turnout_2024'),PCT],['Turnout 2022 (midterm)',x=>e(x,'turnout_2022'),PCT],['Median age',x=>d(x,'Median age'),v=>v.toFixed(1)],['Hispanic',x=>d(x,'Hispanic (%)'),PCT],['White, non-Hispanic',x=>d(x,'Non-Hispanic White (%)'),PCT],['Black, non-Hispanic',x=>d(x,'Non-Hispanic Black (%)'),PCT],['Asian, non-Hispanic',x=>d(x,'Non-Hispanic Asian (%)'),PCT],['Median household income',x=>d(x,'Median household income ($)'),USD],['Poverty rate',x=>d(x,'Poverty rate (%)'),PCT],["Bachelor's degree or higher",x=>d(x,"Bachelor's degree or higher, 25+ (%)"),PCT],['Unemployment',x=>d(x,'Unemployment rate (%)'),PCT],['Homeownership',x=>d(x,'Homeownership rate (%)'),PCT]])
  +`<div class="ccnote">Largest industries (share of employed residents): ${topInd(f,4).map(x=>esc(x[0])+' '+PCT0(x[1])).join(' · ')}.</div>`
  +(()=>{const ps=PL.filter(p=>p[1]===f).sort((a,b)=>(b[5]||0)-(a[5]||0));if(!ps.length)return '';const show=ps.slice(0,12);return `<div class="ccnote"><b>Cities and places</b> (${num(ps.length)}): ${show.map(p=>esc(p[0])+(p[4]==='CDP'?' (community)':p[4]==='city'?'':' ('+esc(p[4])+')')).join(', ')}${ps.length>12?' and '+num(ps.length-12)+' more':''}. Census 2024 Gazetteer; a place that straddles counties is listed under the county of its center point.</div>`;})()
  +H('Key changes over time')+cmpTable(f,[['Population growth 2020 to 2025',x=>d(x,'Pop. change 2020-2025 (%)'),SPCT],['Registration growth 2020 to 2024',x=>e(x,'registration_growth_2020_2024'),SPCT],['Registration growth minus population growth',x=>x==='48'?TEXAS.reg_vs_pop:V[x].regVsPop,PTS],['Republican presidential change 2020 to 2024',x=>e(x,'pres_R_change_2020_2024'),PTS],['Presidential margin change 2016 to 2024',x=>e(x,'pres_margin_change_2016_2024'),PTS],['Midterm turnout change 2018 to 2022',x=>e(x,'turnout_change_2018_2022'),PTS]])
  +`<div class="ccnote">Sources: Texas Demographic Center preliminary 2025 estimates; ACS 2020-24 five-year; Texas Secretary of State registration and canvass; Texas Legislative Council county subtotals 2020-24.</div>`;}
const PAIRS=[['2020-2024','2020 vs 2024','pres'],['2016-2020','2016 vs 2020','pres'],['2018-2022','2018 vs 2022','gov'],['2014-2018','2014 vs 2018','gov']];
function tabElections(f){const c=E.counties[f]||{};const [a,b]=ST.pair.split('-').map(Number);const kind=PAIRS.find(p=>p[0]===ST.pair)[2];const RN={2016:'Trump',2020:'Trump',2024:'Trump',2014:'Abbott',2018:'Abbott',2022:'Abbott'},DN={2016:'Clinton',2020:'Biden',2024:'Harris',2014:'Davis',2018:'Valdez',2022:"O'Rourke"};
  const rows=kind==='pres'?[[`Republican share (${RN[a]} / ${RN[b]})`,x=>e(x,'pres_R_'+a),x=>e(x,'pres_R_'+b),PCT],[`Democratic share (${DN[a]} / ${DN[b]})`,x=>e(x,'pres_D_'+a),x=>e(x,'pres_D_'+b),PCT],['Republican votes',x=>e(x,'pres_R_votes_'+a),x=>e(x,'pres_R_votes_'+b),num],['Democratic votes',x=>e(x,'pres_D_votes_'+a),x=>e(x,'pres_D_votes_'+b),num],['Margin',x=>e(x,'pres_margin_'+a),x=>e(x,'pres_margin_'+b),RM],['Turnout',x=>e(x,'turnout_'+a),x=>e(x,'turnout_'+b),PCT],['Registered voters',x=>e(x,'registered_'+a),x=>e(x,'registered_'+b),num]]
    :[[`Republican share (${RN[a]} / ${RN[b]})`,x=>e(x,'gov_R_'+a),x=>e(x,'gov_R_'+b),PCT],[`Democratic share (${DN[a]} / ${DN[b]})`,x=>e(x,'gov_D_'+a),x=>e(x,'gov_D_'+b),PCT],['Republican votes',x=>e(x,'gov_R_votes_'+a),x=>e(x,'gov_R_votes_'+b),num],['Democratic votes',x=>e(x,'gov_D_votes_'+a),x=>e(x,'gov_D_votes_'+b),num],['Governor margin (R minus D)',x=>e(x,'gov_margin_'+a),x=>e(x,'gov_margin_'+b),RM],['Turnout',x=>e(x,'turnout_'+a),x=>e(x,'turnout_'+b),PCT],['Registered voters',x=>e(x,'registered_'+a),x=>e(x,'registered_'+b),num]];
  const cols=[f].concat(ST.cmp.filter(x=>x!==f)).concat(['48']);const chg=(fa,fb,x,fmt)=>{const va=fa(x),vb=fb(x);if(va==null||vb==null)return '—';return fmt===num?SPCT(vb/va-1):fmt===PCT||fmt===RM?PTS(vb-va):fmt(vb-va);};
  const pairTable=`<table class="cmp"><tr><th>Measure</th>${cols.map(x=>`<th>${x==='48'?'Texas':esc(cname[x])}<br><small>${a} → ${b}</small></th>`).join('')}</tr>${rows.map(([lab,fa,fb,fmt])=>`<tr><td>${lab}</td>${cols.map((x,i)=>{const va=fa(x),vb=fb(x);return `<td${i===0?' class="me"':''}>${va==null?'—':fmt(va)} → ${vb==null?'—':fmt(vb)}<br><small>${chg(fa,fb,x,fmt)}</small></td>`;}).join('')}</tr>`).join('')}</table>`;
  const votes=(r,d)=>x=>[e(x,r),e(x,d)],vfmt=v=>v[0]==null?'—':num(v[0])+' / '+num(v[1]);
  return H('How politically active is the county, and how has it voted?')+H('How did the county vote most recently?')+cmpTable(f,[['2024 President: Trump',x=>e(x,'pres_R_2024'),PCT],['2024 President: Harris',x=>e(x,'pres_D_2024'),PCT],['2024 President: margin',x=>e(x,'pres_margin_2024'),v=>RMN(v,2024,'pres')],['2024 votes (Trump / Harris)',votes('pres_R_votes_2024','pres_D_votes_2024'),vfmt],['2022 Governor: Abbott',x=>e(x,'gov_R_2022'),PCT],["2022 Governor: O'Rourke",x=>e(x,'gov_D_2022'),PCT],['2022 Governor: margin',x=>e(x,'gov_margin_2022'),v=>RMN(v,2022,'gov')],["2022 votes (Abbott / O'Rourke)",votes('gov_R_votes_2022','gov_D_votes_2022'),vfmt]])+H('Change between two elections')+pairTable
    +H('Presidential trend')+cmpTable(f,[['Trump 2016',x=>e(x,'pres_R_2016'),PCT],['Trump 2020',x=>e(x,'pres_R_2020'),PCT],['Trump 2024',x=>e(x,'pres_R_2024'),PCT],['Democratic 2016',x=>e(x,'pres_D_2016'),PCT],['Democratic 2020',x=>e(x,'pres_D_2020'),PCT],['Democratic 2024',x=>e(x,'pres_D_2024'),PCT],['Margin 2016',x=>e(x,'pres_margin_2016'),v=>RMN(v,2016,'pres')],['Margin 2020',x=>e(x,'pres_margin_2020'),v=>RMN(v,2020,'pres')],['Margin 2024',x=>e(x,'pres_margin_2024'),v=>RMN(v,2024,'pres')],['Shift 2016 to 2024 (Trump share)',x=>e(x,'pres_R_change_2016_2024'),PTS]])
    +H('Midterms and other statewide races')+cmpTable(f,[['Governor 2018 margin',x=>e(x,'gov_margin_2018'),v=>RMN(v,2018,'gov')],['Governor 2022 margin',x=>e(x,'gov_margin_2022'),v=>RMN(v,2022,'gov')],['Governor swing 2018 to 2022',x=>e(x,'gov_margin_change_2018_2022'),PTS],['U.S. Senate 2018 margin',x=>e(x,'sen_margin_2018'),v=>RMN(v,2018,'sen')],['U.S. Senate 2020 margin',x=>e(x,'sen_margin_2020'),v=>RMN(v,2020,'sen')],['U.S. Senate 2024 margin',x=>e(x,'sen_margin_2024'),v=>RMN(v,2024,'sen')],['Turnout 2018',x=>e(x,'turnout_2018'),PCT],['Turnout 2022',x=>e(x,'turnout_2022'),PCT],['Primary turnout 2018 (D + R)',x=>e(x,'primary_turnout_2018'),PCT],['Democratic share of 2018 primary votes',x=>e(x,'primary_D_share_2018'),PCT]])
    +`<div class="ccnote">Margins are Republican minus Democratic share of all votes; changes in points; turnout = top-race votes / registered voters. SOS canvass 2006-2018, TLC county subtotals 2020-2024, SOS county pages for the 2014-2018 primaries.</div>`;}
// one candidate: name, party, and the totals from the TEC or FEC when there are any
const candRow=(cd,i,n,f)=>`<div class="org">${cd[3]!=null?`<small>#${i+1} of ${n}</small> `:''}<b>${esc(cd[0])}</b> <span style="color:${cd[2]==='REP'?'#a91b1b':cd[2]==='DEM'?'#1b4fa6':'var(--ink3)'};font-weight:600">${esc(cd[2])}</span>${cd[3]!=null?`<br>Raised ${USD(cd[3])} · Cash on hand ${cd[4]!=null?USD(cd[4]):'—'} · Spent ${cd[10]!=null?USD(cd[10]):'—'}${cd[12]?' · Loans '+USD(cd[12]):''}<br><small>${(cd[7]||'').includes('FEC')?'FEC 2025-26 cycle totals':'Candidate account (TEC)'}, filed through ${esc(cd[5]||'—')}${cd[8]?'; associated committees: '+esc(cd[8])+' (raised '+(cd[9]!=null?USD(cd[9]):'—')+' since 2025)':''}</small>`:`<br><small>${(cd[7]||'').includes('FEC')?'no FEC summary':'files with a county or local authority; not in the TEC export'}</small>`}${(()=>{const x=f?fromCounty(cd,f):null;return x?`<br><small class="fromc">From ${esc(cname[f])} County donors: <b>${USD(x[0])}</b> in 2026 (${num(x[1])} gifts)${shareOf(x[0],cd)?', '+shareOf(x[0],cd)+' of the total':''}; ${USD(x[2])} since 2025</small>`:f&&cd[3]!=null&&!(cd[7]||'').includes('FEC')?`<br><small class="fromc">No itemized gifts from ${esc(cname[f])} County donors</small>`:'';})()}</div>`;
function tabMoney(f){const bc=B.counties[f]||{cands:[]};const byOff={};bc.cands.forEach(i=>{const cd=B.cands[i];const o=B.offices[cd[1]];(byOff[o[0]+'|'+o[1]]=byOff[o[0]+'|'+o[1]]||[]).push(cd);});
  const races=Object.keys(byOff).filter(k=>DOWN.has(k.split('|')[1])).map(k=>{const cs=byOff[k].slice().sort((a,b)=>(b[3]||0)-(a[3]||0));return {name:k.split('|')[0],level:k.split('|')[1],cs,tot:cs.reduce((a,x)=>a+(x[3]||0),0),any:cs.some(x=>x[3]!=null)};}).sort((a,b)=>b.tot-a.tot||a.name.localeCompare(b.name));
  const row=candRow;
  const fed=Object.keys(byOff).filter(k=>k.endsWith('|Federal')),stw=Object.keys(byOff).filter(k=>k.endsWith('|Statewide'));
  const givers=[];Object.keys(CT.cands).forEach(i=>{const x=CT.cands[i][f];if(x&&x[0]>0)givers.push([+i,x]);});Object.keys(CT.spacs).forEach(i=>{const x=CT.spacs[i][f];if(!x||!x[0])return;const g=givers.find(y=>y[0]===+i);if(g)g[1]=g[1].map((v,k)=>v+x[k]);else givers.push([+i,x.slice()]);});givers.sort((a,b)=>b[1][0]-a[1][0]);
  return H('Where is campaign money flowing?')+`<div class="box"><b>${num(V[f].moneyN)}</b> candidates in state-district races on this ballot report <b>${USDK(V[f].money)}</b> raised in 2026 (TEC). Best-funded race: ${esc(topRace(f))}.</div>`
    +H('Who gives here?')+`<div class="box">Donors in ${esc(cname[f])} County gave <b>${USDK(V[f].contrib)}</b> in itemized contributions to 2026 state candidates in 2026 (${num(V[f].contribN)} gifts to ${num(givers.length)} candidates or their committees): <b>${USDK(V[f].contribR)}</b> to Republican candidates and <b>${USDK(V[f].contribD)}</b> to Democratic candidates${V[f].govDshare!=null?`; in the governor's race ${PCT0(V[f].govDshare)} of the county's dollars went to the Democratic candidate`:''}.</div>`
    +(givers.length?`<div class="cat">Candidates receiving the most from ${esc(cname[f])} County donors</div>`+givers.slice(0,10).map(([i,x],k)=>{const cd=B.cands[i];return `<div class="org"><small>#${k+1}</small> <b>${esc(cd[0])}</b> <span style="color:${cd[2]==='REP'?'#a91b1b':cd[2]==='DEM'?'#1b4fa6':'var(--ink3)'};font-weight:600">${esc(cd[2])}</span> <small>· ${esc(title(B.offices[cd[1]][0]))}</small><br><small>${USD(x[0])} in 2026 (${num(x[1])} gifts)${shareOf(x[0],cd)?' · '+shareOf(x[0],cd)+' of what the candidate raised':''}${cd[8]?' · includes '+esc(cd[8].replace(/\s*\(\d{8}\)/g,''))+'':''} · ${USD(x[2])} since 2025</small></div>`;}).join(''):'<div class="ccnote">No itemized contributions from this county\'s donors in 2026.</div>')
    +(races.length?races.map(r=>`<div class="cat">${esc(title(r.name))} <small>· ${r.any?USDK(r.tot)+' raised in 2026':'no TEC data'}</small></div>${r.any&&r.level==='State district'&&r.tot>=HIGH?`<div class="ccnote"><b>One of the higher-funded down-ballot races affecting the county</b> (top quarter of State House, Senate and SBOE race totals statewide, ${USDK(HIGH)} and up).</div>`:''}${r.cs.map((cd,i)=>row(cd,i,r.cs.length,f)).join('')}`).join(''):'<div class="ccnote">No district-level races on this ballot.</div>')
    +`<details><summary>U.S. House and Senate on this ballot (FEC, 2025-26 cycle)</summary>${fed.map(k=>`<div class="cat">${esc(title(k.split('|')[0]))}</div>${byOff[k].slice().sort((a,b)=>(b[3]||0)-(a[3]||0)).map((cd,i)=>row(cd,i,byOff[k].length,f)).join('')}`).join('')}</details>`
    +`<details><summary>Statewide races (same on every ballot)</summary>${stw.map(k=>`<div class="cat">${esc(title(k.split('|')[0]))}</div>${byOff[k].slice().sort((a,b)=>(b[3]||0)-(a[3]||0)).map((cd,i)=>row(cd,i,byOff[k].length,f)).join('')}`).join('')}</details>`
    +`<div class="ccnote">Texas Ethics Commission bulk export as of 2026-09-26 (2026 year to date through each candidate's latest report); FEC bulk candidate summary as of 2026-09-28 (cycle totals). County offices file locally and are blank. "From county donors" = itemized contributions (TEC Schedule A) placed by the donor\'s ZIP or city; unitemized gifts and federal candidates\' donors are not placed.</div>`;}
const LEVELS=['Federal','Statewide','State district','Judicial district','District attorney','County / precinct'];
function chairHTML(f){const ch=(B.counties[f]||{}).chair||{};return ch.name?`<div class="box"><b>Democratic county chair</b><br>${esc(ch.name)}${ch.email?'<br><small>'+ch.email.split(' / ').map(m=>'<a href="mailto:'+esc(m.trim())+'">'+esc(m.trim())+'</a>').join(' / ')+'</small>':''}${ch.phone?'<br><small>'+esc(ch.phone)+'</small>':''}<br><small>Texas Democratic Party county chair directory</small></div>`:`<div class="box"><b>Democratic county chair</b><br><small>${esc(ch.status||'No chair listed')}</small></div>`;}
function tabBallot(f){const bc=B.counties[f]||{cands:[]};const byOff={};const order=[];bc.cands.forEach(i=>{const cd=B.cands[i],o=B.offices[cd[1]];const k=o[0]+'|'+o[1];if(!byOff[k]){byOff[k]=[];order.push(k);}byOff[k].push(cd);});
  const counts=LEVELS.map(l=>[l,order.filter(k=>k.endsWith('|'+l)).reduce((a,k)=>a+byOff[k].length,0)]).filter(x=>x[1]);
  return H('What is on the 2026 ballot, and who are the party contacts?')+chairHTML(f)+`<div class="box"><b>${num(bc.cands.length)}</b> candidates for <b>${num(order.length)}</b> offices on the certified 2026 general-election ballot: ${counts.map(([l,n])=>n+' '+l.toLowerCase()).join(', ')}.</div>`
    +LEVELS.map(l=>{const ks=order.filter(k=>k.endsWith('|'+l));if(!ks.length)return '';return `<div class="cat">${esc(l)}</div>`+ks.map(k=>{const cs=byOff[k];const money=cs.some(c=>c[3]!=null);const sorted=money?cs.slice().sort((a,b)=>(b[3]||0)-(a[3]||0)):cs;
      return `<div class="race"><b>${esc(title(k.split('|')[0]))}</b>${cs.length===1?' <small>· unopposed</small>':''}${money?' <small>· '+USDK(cs.reduce((a,x)=>a+(x[3]||0),0))+' raised</small>':''}</div>`+sorted.map((cd,i)=>candRow(cd,i,cs.length,f)).join('');}).join('');}).join('')
    +`<div class="ccnote">Ballot: Texas Secretary of State certification of ${esc(B.ballot_cert)}. Totals: ${esc(B.fund_asof)}; FEC 2025-26 cycle totals for federal candidates. County and precinct candidates file with the county clerk, so their totals are not online.</div>`;}
function orgRow(o){return `<div class="org"><b>${esc(o.org)}</b>${o.chapter?' <small>· '+esc(o.chapter)+'</small>':''}${o.leader?'<br>'+esc(o.leader)+(o.title?', '+esc(o.title):''):''}${o.phone||o.email||o.web?'<br><small>'+[o.phone?esc(o.phone):'',o.email?'<a href="mailto:'+esc(o.email)+'">'+esc(o.email)+'</a>':'',o.web?'<a href="'+esc(o.web)+'" target="_blank" rel="noopener">website ↗</a>':''].filter(Boolean).join(' · ')+'</small>':''}${o.addr?'<br><small>'+esc(o.addr)+'</small>':''}<br><small>${esc(o.constituency||'')} · reach: ${esc(o.cover||'unknown')} · evidence: ${esc(o.evidence||'unknown')}</small>${o.notes?'<br><small>'+esc(o.notes)+'</small>':''}<br><small>Source: ${o.src?'<a href="'+esc(o.src.split(' ')[0])+'" target="_blank" rel="noopener">'+esc(o.src.replace(/^https?:\/\/(www\.)?/,'').split('/')[0])+' ↗</a>':'—'}${o.verified?' · '+esc(o.verified):''}</small></div>`;}
function contactsHTML(f){const ch=(B.counties[f]||{}).chair||{};const orgs=(ORG[f]||[]).filter(o=>o.leader||o.phone||o.email).sort((a,b)=>(b.leader?1:0)-(a.leader?1:0)||CATS.indexOf(a.cat)-CATS.indexOf(b.cat));const rows=[];
  if(ch.name)rows.push(`<div class="org"><b>${esc(ch.name)}</b> <small>· Democratic county chair</small><br><small>${[ch.phone?esc(ch.phone):'',ch.email?ch.email.split(' / ').map(m=>'<a href="mailto:'+esc(m.trim())+'">'+esc(m.trim())+'</a>').join(' / '):''].filter(Boolean).join(' · ')}</small></div>`);
  orgs.slice(0,12).forEach(o=>rows.push(`<div class="org"><b>${o.leader?esc(o.leader):esc(o.org)}</b> <small>· ${o.leader?esc(o.title||'')+(o.title?', ':'')+esc(o.org):esc(o.cat)}</small><br><small>${[o.phone?esc(o.phone):'',o.email?'<a href="mailto:'+esc(o.email)+'">'+esc(o.email)+'</a>':'',o.web?'<a href="'+esc(o.web)+'" target="_blank" rel="noopener">website ↗</a>':''].filter(Boolean).join(' · ')}${o.notes&&/verify/i.test(o.notes)?' · <i>verify before contacting</i>':''}</small></div>`));
  return rows.length?H('Who should I talk to?')+`<div class="ccnote">Public-facing contact points: the county chair first, then organizations with a named leader, then the rest with a phone or email. Every organization is listed by sector below with its source.</div>`+rows.join(''):'';}
function tabCommunity(f){const orgs=ORG[f]||[];const by={};orgs.forEach(o=>{(by[o.cat]=by[o.cat]||[]).push(o);});const order=c=>{const i=CATS.indexOf(c);return i<0?99:i;};
  return contactsHTML(f)+H('Which organizations are present here?')+`<div class="ccnote">${esc(O.definition||'')} <i>${esc(O.caution||'')}</i></div>`+(orgs.length?Object.keys(by).sort((a,b)=>order(a)-order(b)).map(ct=>`<div class="cat">${esc(ct)} <small>(${by[ct].length})</small></div>${by[ct].map(orgRow).join('')}`).join(''):'<div class="ccnote">No organizations collected for this county yet. The statewide directories gathered so far had no entry here; add local groups where a roundtable is planned.</div>')
    +`<div class="ccnote">Collected so far: ${esc((O.waves||[]).map(w=>w.done?w.label+' ✓':w.label+' (pending)').join(' · '))}.</div>`;}
function tabDistricts(f){const plan=ST.dmap;const parts=(X.counties[f]||{})[plan]||[];const lab=plan===NEW?'2026 map (PLANC2333)':'2024 map (PLANC2193)';
  const rows=parts.map(([n,p,sh])=>[CM.districtName(plan,n)+(sh<0.995?' ('+PCT0(sh)+' of county)':''),RM(marg(plan,2016,'pres',n)),RM(marg(plan,2020,'pres',n)),RM(marg(plan,2024,'pres',n)),RM(marg(plan,2022,'gov',n)),RM(marg(plan,2024,'sen',n))]);
  return H('What changed because of redistricting?')
    +`<div class="box"><b>2024 map (PLANC2193):</b> ${((X.counties[f]||{})[OLD]||[]).map(([n,p,sh])=>'CD '+n+(sh<0.995?' ('+PCT0(sh)+')':'')).join(' + ')||'—'}<br><b>2026 map (PLANC2333):</b> ${((X.counties[f]||{})[NEW]||[]).map(([n,p,sh])=>'CD '+n+(sh<0.995?' ('+PCT0(sh)+')':'')).join(' + ')||'—'}<br>${V[f].cdChg>=0.999?'<b>The whole county has a new district number under the 2026 map.</b>':V[f].cdChg>0?'<b>The county is split differently under the 2026 map</b> ('+PCT0(V[f].cdChg)+' of residents have a new district number).':'The district number here did not change under the 2026 map.'}${V[f].leanChg!=null?'<br>2024 presidential vote under the old district: <b>'+RM(V[f].leanOld)+'</b>; re-tabulated into the 2026 district: <b>'+RM(V[f].leanNew)+'</b>.':''}</div>`
    +H('Districts affecting the county on the '+lab)+`<table class="cmp"><tr><th>District</th><th>Pres. 2016</th><th>Pres. 2020</th><th>Pres. 2024</th><th>Gov. 2022</th><th>Sen. 2024</th></tr>${rows.map(r=>`<tr>${r.map((c,i)=>`<td${i===0?' class="me"':''}>${c}</td>`).join('')}</tr>`).join('')}</table>`
    +parts.map(([n])=>CM.districtRow(plan,n,RM(marg(plan,2024,'pres',n)),'open this district')).join('')
    +`<div class="ccnote">Legislative districts: ${['PLANH2316','PLANS2168','PLANE2106'].map(pl=>((X.counties[f]||{})[pl]||[]).map(([n,p,sh])=>CM.districtName(pl,n)+(sh<0.995?' ('+PCT0(sh)+')':'')).join(', ')).filter(Boolean).join(' · ')||'—'}. Results on the 2026 lines are Texas Legislative Council re-tabulations of actual votes (Red-206); county shares are 2020 Census residents.</div>`;}
function tabWater(f){const w=W[f]||{};const aq=(AQ[f]||{}).aq||[];const uses=o=>Object.entries(o||{}).sort((a,b)=>b[1]-a[1]).slice(0,4).map(([k,v])=>k+' '+num(v)).join(' · ');
  return H('What water and aquifer context matters?')+`<div class="box"><b>Rain:</b> ${w.p!=null?w.p+'% of the county\'s usual year in the last twelve months':'no data'}${w.r?' (usual: '+w.r+' inches a year, 1991-2020 average)':''}.<br><b>Groundwater:</b> ${aq.length?aq.map(a=>esc(a[0])+' ('+PCT0(a[2])+' of the county'+(a[1]==='minor'?', minor aquifer':'')+')').join('; '):'no mapped aquifer'}.<br><b>Wells:</b> ${w.w!=null?num(w.w)+' on record':'—'}; ${w.nw!=null?num(w.nw)+' drilled since 2020':'—'}${w.nwu?' ('+uses(w.nwu)+')':''}.</div>`
    +cmpTable(f,[['Rain, last 12 months vs. usual',x=>x==='48'?null:V[x].rainPct,v=>v+'%'],['Usual rainfall (in/yr)',x=>x==='48'?null:V[x].rain,v=>v.toFixed(1)],['Wells on record',x=>x==='48'?WD.total:V[x].wells,num],['Wells drilled since 2020',x=>x==='48'?WD.nw_total:V[x].wellsNew,num],['Data center projects',x=>x==='48'?TEXAS.dc_n:V[x].dcN,num]])
    +`<div class="acts"><button type="button" data-layer="rivers">${CM.state.rivers?'Hide':'Show'} rivers &amp; lakes</button><button type="button" data-layer="basins">${CM.state.basins?'Hide':'Show'} river basins</button><button type="button" data-layer="aquifers">${CM.state.aquifers?'Hide':'Show'} aquifers on the map</button><a href="texas_aquifers_map.html" target="_blank" rel="noopener">Aquifer map ↗</a><a href="texas_rainfall_map.html" target="_blank" rel="noopener">Rainfall map ↗</a><a href="texas_wells_map.html" target="_blank" rel="noopener">Wells map ↗</a></div>`
    +`<div class="ccnote">Rain: PRISM Climate Group (county means, ${esc(WD.generated||'2026-09-25')}). Wells: TWDB groundwater database and driller reports. Aquifers: TWDB major and minor aquifer outlines, share of county area by grid sampling.</div>`;}
function tabDC(f){const list=(DCC[f]||[]).slice().sort((a,b)=>(b.mw||0)-(a.mw||0));const LBL={operating:'Operating',under_construction:'Under construction',proposed:'Proposed'};
  return H('What data-center activity is there?')+`<div class="box"><b>${num(list.length)}</b> project${list.length===1?'':'s'} tracked${list.length?': '+Object.entries(list.reduce((a,s)=>{a[s.status]=(a[s.status]||0)+1;return a;},{})).map(([k,v])=>v+' '+(LBL[k]||k).toLowerCase()).join(', '):''}${V[f].dcMW?'; <b>'+num(V[f].dcMW)+' MW</b> announced where reported':''}.<br><b>Water context:</b> ${aqList(f)}; rain last 12 months ${V[f].rainPct!=null?V[f].rainPct+'% of usual':'—'}.</div>`
    +(list.length?list.map(s=>`<div class="org"><b>${esc(s.name)}</b>${s.hot?' <small style="color:var(--hot)">flagged</small>':''}<br><small>${esc(s.operator||'operator not listed')} · ${esc(LBL[s.status]||s.status)} · ${esc(s.city||'')}${s.mw?' · '+num(s.mw)+' MW':''}${s.acres?' · '+num(s.acres)+' acres':''}</small></div>`).join(''):'<div class="ccnote">No data center project tracked in this county.</div>')
    +`<div class="acts"><button type="button" data-layer="pins">${CM.state.pins?'Hide':'Show'} project dots on the map</button><a href="texas_data_center_map.html" target="_blank" rel="noopener">Data center map ↗</a></div>`
    +`<div class="ccnote">Source: Texas Data Center Watch project list (developer, status, announced power, site). Incentives, local decisions and timelines are not in that extract; each project's news links are on the data center map.</div>`;}
document.addEventListener('click',ev=>{const p=ev.target.closest('[data-pair]');if(p){ST.pair=p.dataset.pair;renderPanel();renderRibbon();return;}
  const m=ev.target.closest('[data-dmap]');if(m){ST.dmap=m.dataset.dmap;CM.setPlan(ST.dmap);renderRibbon();renderPanel();setHash();return;}
  const l=ev.target.closest('[data-layer]');if(l){const k=l.dataset.layer;const o={};o[k]=!CM.state[k];CM.setLayers(o);renderRibbon();renderPanel();setHash();return;}
  const a=ev.target.closest('[data-act]');if(a){if(a.dataset.act==='cmp')addCompare(ST.f);else if(a.dataset.act==='brief')openBrief(ST.f);else if(a.dataset.act==='back')back();return;}});
// ---- panel ----
// ---- the Texas page (home): statewide findings and ranked lists, one block per tab ----
const sumBy=fn=>F.reduce((a,f)=>{const x=fn(f);return a+(x||0);},0);const nv=v=>v!=null?' ('+num(v)+')':'';
function homeKnow(){const out=[];const st=(t,ev)=>out.push({t,ev});const mv=F.map(f=>[f,e(f,'pres_R_change_2020_2024')]).filter(x=>x[1]!=null).sort((a,b)=>b[1]-a[1]);
  st(`Voter registration ${TEXAS.reg_since_2024>=0?'grew':'fell'} ${SPCT(TEXAS.reg_since_2024)} from the 2024 election to March 2026`,[['Nov. 2022',num(S.registered_2022)],['Nov. 2024',num(S.registered_2024)],['March 2026',num(S.registered_march_2026),1],['Change since Nov. 2024',SPCT(TEXAS.reg_since_2024),1],['Since the 2022 midterm',SPCT(TEXAS.reg_since_2022)],['On the suspense list',num(S.suspense_march_2026)+' ('+PCT(S.suspense_march_2026/S.registered_march_2026)+')']]);
  st(`Midterm turnout ${S.turnout_change_2018_2022<0?'fell':'rose'} from 2018 to 2022`,[['2018',PCT(S.turnout_2018)],['2022',PCT(S.turnout_2022)],['Change',PTS(S.turnout_change_2018_2022),1],['Counties where it fell',num(F.filter(f=>(e(f,'turnout_change_2018_2022')||0)<0).length)+' of '+num(F.length)]]);
  st(`Presidential turnout ${S.turnout_change_2020_2024<0?'fell':'rose'} from 2020 to 2024`,[['2020',PCT(S.turnout_2020)],['2024',PCT(S.turnout_2024)],['Change',PTS(S.turnout_change_2020_2024),1],['Counties where it fell',num(F.filter(f=>(e(f,'turnout_change_2020_2024')||0)<0).length)+' of '+num(F.length)]]);
  st(`Trump ${S.pres_R_change_2020_2024>=0?'gained':'lost'} ground in ${num(mv.filter(x=>x[1]>0).length)} of ${num(mv.length)} counties from 2020 to 2024`,[['Texas 2020',PCT(S.pres_R_2020)],['Texas 2024',PCT(S.pres_R_2024)],['Change',PTS(S.pres_R_change_2020_2024),1],['Furthest toward Trump',cname[mv[0][0]]+' ('+PTS(mv[0][1])+')'],['Furthest toward Democrats',cname[mv[mv.length-1][0]]+' ('+PTS(mv[mv.length-1][1])+')']]);
  st(`${S.pres_margin_2024>0?'Republicans':'Democrats'} carried Texas in 2024`,[['Republican',PCT(S.pres_R_2024)+nv(S.pres_R_votes_2024)],['Democratic',PCT(S.pres_D_2024)+nv(S.pres_D_votes_2024)],['Margin',RMN(S.pres_margin_2024,2024,'pres'),1],['Counties won by Harris',num(F.filter(f=>(e(f,'pres_margin_2024')||0)<0).length)]]);
  if(S.gov_margin_2022!=null)st(`Abbott won the 2022 governor's race statewide`,[['Abbott',PCT(S.gov_R_2022)+nv(S.gov_R_votes_2022)],["O'Rourke",PCT(S.gov_D_2022)+nv(S.gov_D_votes_2022)],['Margin',RMN(S.gov_margin_2022,2022,'gov'),1],["Counties won by O'Rourke",num(F.filter(f=>(e(f,'gov_margin_2022')||0)<0).length)]]);
  const chg=F.filter(f=>(X.changed[f]||0)>0).length,full=F.filter(f=>(X.changed[f]||0)>=0.999).length;
  st(`${num(chg)} counties have residents in a differently numbered congressional district under the 2026 map`,[['Fully renumbered',num(full)],['Partly',num(chg-full)],['Unchanged',num(F.length-chg)],['Maps','PLANC2333 (2026) vs PLANC2193 (2024)']]);
  const leg=Object.keys(raceTot).filter(k=>B.offices.some(o=>o[0]===k&&o[1]==='State district')).sort((a,b)=>raceTot[b]-raceTot[a]);const legSum=leg.reduce((a,k)=>a+raceTot[k],0);
  st(`Texas donors gave ${USDK(sumBy(f=>V[f].contribR))} to Republican and ${USDK(sumBy(f=>V[f].contribD))} to Democratic candidates for state office in 2026`,[['Republican',USDK(sumBy(f=>V[f].contribR)),1],['Democratic',USDK(sumBy(f=>V[f].contribD)),1],['Itemized gifts placed in a county',num(sumBy(f=>V[f].contribN))],['Counties giving more to Democrats',num(F.filter(f=>V[f].contribD>V[f].contribR).length)]]);
  st(`State-district candidates have raised ${USDK(legSum)} in 2026`,[['Races reporting',num(leg.length)],['Raised',USDK(legSum),1],['Best-funded race',leg.length?title(leg[0])+' ('+USDK(raceTot[leg[0]])+')':'—'],['Higher-funded means',USDK(HIGH)+' and up']]);
  const oc=Object.keys(ORG).length,cc=CATS.map(ct=>[ct,(O.orgs||[]).filter(o=>o.cat===ct).length]).filter(x=>x[1]);
  st(`${num((O.orgs||[]).length)} community organizations are listed across ${num(oc)} counties`,[['Listed',num((O.orgs||[]).length),1],['Sectors',cc.map(([c,n])=>c+' ('+num(n)+')').join(', ')],['Counties with none',num(F.length-oc)]]);
  const dry=F.filter(f=>V[f].rainPct!=null&&V[f].rainPct<80).length,dcC=Object.keys(DCC).length;
  st(`${num(dry)} counties had a dry year and ${num(dcC)} have data center projects`,[['Rain under 80% of usual',num(dry)+' counties',dry?1:0],['Data center projects',num(sumBy(f=>V[f].dcN))+' in '+num(dcC)+' counties'],['Announced power',num(Math.round(sumBy(f=>V[f].dcMW)))+' MW'],['Wells drilled since 2020',num(sumBy(f=>V[f].wellsNew))]]);
  return out;}
const rowsTX=rows=>`<table class="cmp"><tr><th>Measure</th><th>Texas</th></tr>${rows.map(([lab,fn,fmt])=>{const v=fn('48');return `<tr><td>${lab}</td><td class="me">${v==null||(typeof v==='number'&&isNaN(v))?'—':fmt(v)}</td></tr>`;}).join('')}</table>`;
const topList=(t,n,fn,fmt,sub,desc=true)=>{const l=F.map(f=>[f,fn(f)]).filter(x=>x[1]!=null&&!isNaN(x[1])).sort((a,b)=>desc?b[1]-a[1]:a[1]-b[1]).slice(0,n);return H(t)+l.map(([f,v])=>CM.countyRow(f,fmt(v),sub?sub(f):'')).join('');};
function homeOverview(){return H('Who lives in Texas?')+rowsTX(ROWS)+`<div class="ccnote">Click a county on the map or search above for its page; every county table shows the Texas figure alongside.</div>`;}
function homeElections(){const rows=[];[2024,2020,2016,2012,2008].forEach(y=>{if(S['pres_R_'+y]!=null)rows.push([y,'President',PCT(S['pres_R_'+y]),PCT(S['pres_D_'+y]),RMN(S['pres_margin_'+y],y,'pres'),PCT(S['turnout_'+y])]);});[2022,2018,2014,2010,2006].forEach(y=>{if(S['gov_R_'+y]!=null)rows.push([y,'Governor',PCT(S['gov_R_'+y]),PCT(S['gov_D_'+y]),RMN(S['gov_margin_'+y],y,'gov'),PCT(S['turnout_'+y])]);});[2024,2020,2018,2014,2012,2008,2006].forEach(y=>{if(S['sen_R_'+y]!=null)rows.push([y,'U.S. Senate',PCT(S['sen_R_'+y]),PCT(S['sen_D_'+y]),RMN(S['sen_margin_'+y],y,'sen'),PCT(S['turnout_'+y])]);});rows.sort((a,b)=>b[0]-a[0]);
  return H('How politically active is Texas, and how has it voted?')+`<table class="cmp"><tr><th style="text-align:left">Year</th><th style="text-align:left">Race</th><th>Rep.</th><th>Dem.</th><th>Margin</th><th>Turnout</th></tr>${rows.map(r=>`<tr>${r.map((c,i)=>`<td${i<2?' style="text-align:left"':''}>${c}</td>`).join('')}</tr>`).join('')}</table>`
    +topList('Fastest toward Trump, 2020 to 2024',10,f=>e(f,'pres_R_change_2020_2024'),PTS)+topList('Fastest toward Democrats, 2020 to 2024',10,f=>e(f,'pres_R_change_2020_2024'),PTS,null,false)
    +topList('Biggest midterm turnout drops, 2018 to 2022',10,f=>e(f,'turnout_change_2018_2022'),PTS,null,false)+topList('Fastest registration growth, Nov. 2024 to March 2026',10,f=>e(f,'registration_growth_2024_2026'),SPCT)+topList('Fastest registration growth since the 2022 midterm',10,f=>V[f].regSince22,SPCT)
    +`<div class="ccnote">Turnout = top-race votes / registered voters. SOS canvass 2006-2018; TLC county subtotals 2020-2024.</div>`;}
function homeMoney(){const races=Object.entries(raceTot).sort((a,b)=>b[1]-a[1]).slice(0,15);const lvl=k=>(B.offices.find(o=>o[0]===k)||[])[1]||'';
  return H('Where is campaign money flowing?')+`<div class="box"><b>${USDK(Object.values(raceTot).reduce((a,b)=>a+b,0))}</b> raised in 2026 by candidates in ${num(Object.keys(raceTot).length)} state-district, judicial-district and district-attorney races (TEC). A race counts as higher-funded at ${USDK(HIGH)} and up (top quarter of State House, Senate and SBOE races).</div>`
    +`<div class="cat">Best-funded down-ballot races</div>`+races.map(([k,v],i)=>`<div class="org"><small>#${i+1}</small> <b>${esc(title(k))}</b> <small>· ${esc(lvl(k))}</small><br>${USD(v)} raised in 2026 by ${num(B.cands.filter(c=>B.offices[c[1]][0]===k&&c[3]!=null).length)} candidates</div>`).join('')
    +topList('Counties whose donors gave the most to Republican candidates',10,f=>V[f].contribR,USDK,f=>USDK(V[f].contribD)+' to Democrats')+topList('Counties whose donors gave the most to Democratic candidates',10,f=>V[f].contribD,USDK,f=>USDK(V[f].contribR)+' to Republicans')+topList('Counties with the most down-ballot money on the ballot',10,f=>V[f].money,USDK)+`<div class="ccnote">A district race counts in full for every county it touches. Statewide candidates are on the Ballot tab.</div>`;}
function homeBallot(){const byOff={};const order=[];B.cands.forEach(cd=>{const o=B.offices[cd[1]];if(o[1]!=='Statewide'&&o[0]!=='U. S. SENATOR')return;if(!byOff[o[0]]){byOff[o[0]]=[];order.push(o[0]);}byOff[o[0]].push(cd);});
  return H('What is on the 2026 statewide ballot?')+`<div class="box"><b>${num(order.length)}</b> statewide and U.S. Senate races with <b>${num(order.reduce((a,k)=>a+byOff[k].length,0))}</b> candidates. Open a county for its full ballot: U.S. House, legislative, judicial, district attorney, county and precinct races, and the Democratic county chair.</div>`
    +order.map(k=>{const cs=byOff[k].slice().sort((a,b)=>(b[3]||0)-(a[3]||0));return `<div class="race"><b>${esc(title(k))}</b> <small>· ${USDK(cs.reduce((a,x)=>a+(x[3]||0),0))} raised</small></div>`+cs.map((cd,i)=>candRow(cd,i,cs.length)).join('');}).join('')
    +`<div class="ccnote">SOS certification of ${esc(B.ballot_cert)}; ${esc(B.fund_asof)}; FEC 2025-26 cycle totals for federal candidates.</div>`;}
function homeCommunity(){const cc=CATS.map(ct=>[ct,(O.orgs||[]).filter(o=>o.cat===ct)]).filter(x=>x[1].length);
  return H('Which organizations are present, statewide?')+`<table class="cmp"><tr><th style="text-align:left">Sector</th><th>Organizations</th><th>Counties</th></tr>${cc.map(([ct,l])=>`<tr><td>${esc(ct)}</td><td>${num(l.length)}</td><td>${num(new Set(l.map(o=>o.f)).size)}</td></tr>`).join('')}</table>`
    +topList('Counties with the most organizations listed',10,f=>V[f].orgs,num)+`<div class="ccnote">${esc(O.caution||'An organization does not control or perfectly represent its members.')}</div>`;}
function homeDistricts(){const plan=ST.dmap;const yr=R[plan]&&R[plan].years[2024];if(!yr)return '';const ds=Object.keys(yr.d).map(n=>[+n,marg(plan,2024,'pres',n)]).filter(x=>x[1]!=null);const close=ds.slice().sort((a,b)=>Math.abs(a[1])-Math.abs(b[1])).slice(0,10);const dem=ds.filter(x=>x[1]<0).length;
  return H('What changed because of redistricting?')
    +`<div class="box">${esc((CM.plan(plan)||{}).label||plan)}: <b>${num(ds.length)}</b> districts. On the 2024 presidential vote ${num(dem)} lean Democratic and ${num(ds.length-dem)} Republican; ${num(ds.filter(x=>Math.abs(x[1])<0.1).length)} are within 10 points.</div>`
    +H('Closest districts, 2024 presidential vote')+close.map(([n,m])=>CM.districtRow(plan,n,RM(m),'')).join('')
    +topList('Counties with the most residents in a new district number',10,f=>X.changed[f],PCT0)+`<div class="ccnote">${esc((R[plan]||{}).basis||'')}.</div>`;}
function homeWater(){return H('What water and aquifer context matters?')+topList('Driest counties, last 12 months vs. usual',10,f=>V[f].rainPct,v=>v+'% of usual',null,false)+topList('Most wells drilled since 2020',10,f=>V[f].wellsNew,num)+`<div class="ccnote">Rain: PRISM county means. Wells: TWDB driller reports. Aquifers are on each county's Water tab.</div>`;}
function homeDC(){const n=sumBy(f=>V[f].dcN),mw=sumBy(f=>V[f].dcMW);return H('What data-center activity is there?')+`<div class="box"><b>${num(n)}</b> projects tracked in ${num(Object.keys(DCC).length)} counties; ${num(Math.round(mw))} MW announced where reported. The Data centers coloring shows the projects as dots.</div>`+topList('Counties with the most projects',10,f=>V[f].dcN,num,f=>V[f].dcMW?num(Math.round(V[f].dcMW))+' MW announced':'')+`<div class="ccnote">Texas Data Center Watch; withdrawn projects excluded.</div>`;}
function renderHome(){const tab={overview:homeOverview,elections:homeElections,money:homeMoney,ballot:homeBallot,community:homeCommunity,districts:homeDistricts,water:homeWater,dc:homeDC}[ST.tab]||homeOverview;
  side.innerHTML=`<div class="detail"><h2>Texas</h2><div class="sub">${num(F.length)} counties · ${num(TXD['Population, July 1 2025 (TDC prelim.)'])} people · ${num(S.registered_march_2026)} registered (March 2026) · 38 congressional districts</div>${ST.tab==='overview'?knowBlock(homeKnow()):''}<div class="cctab">${tab()}</div></div>`;}
function renderPanel(){if(!ST.f){renderHome();return;}
  const f=ST.f;const tab={overview:tabOverview,elections:tabElections,money:tabMoney,ballot:tabBallot,community:tabCommunity,districts:tabDistricts,water:tabWater,dc:tabDC}[ST.tab]||tabOverview;
  side.innerHTML=`<div class="detail"><button class="back" data-act="back">← Texas</button><h2>${esc(cname[f])} County</h2><div class="sub">${esc((RG[f]||{}).Region||'')} · ${num(d(f,'Population, July 1 2025 (TDC prelim.)'))} people · ${num(e(f,'registered_march_2026'))} registered (March 2026) · ${((X.counties[f]||{})[NEW]||[]).map(([n])=>'CD '+n).join(', ')} (2026 map)${ST.place?' · searched: '+esc(ST.place):''}</div>
    <div class="acts phone"><button type="button" data-act="cmp"${ST.cmp.includes(f)||ST.cmp.length>=3?' disabled':''}>${ST.cmp.includes(f)?'In the compare tray':'+ Add to compare'}</button><button type="button" class="primary" data-act="brief">Prepare roundtable</button></div>${ST.tab==='overview'?knowHTML(f):`<details class="knowfold"><summary>What to know · ${know(f).length} findings</summary>${knowHTML(f)}</details>`}<div class="cctab">${tab(f)}</div></div>`;}
function showCounty(f){if(!DM[f])return;ST.f=f;$('sb-cur').textContent=cname[f]+' County';$('side-title').textContent=cname[f]+' County';CM.select(null);CM.highlightDistrict(null);CM.highlightCounty(f);CM.zoomCounty(f);renderPanel();renderTray();setHash();}
function back(){ST.f='';ST.place='';$('sb-cur').textContent='Move over the map to read a county';$('side-title').textContent='Texas';renderRibbon();CM.highlightCounty(null);CM.highlightDistrict(null);CM.fit();renderPanel();renderTray();setHash();}
function showDistrict(plan,n){const cs=CM.districtCounties(plan,n);if(CM.activePlan()!==plan)CM.setPlan(plan);CM.highlightDistrict(plan,n);CM.zoomDistrict(plan,n);renderRibbon();
  const rows=[];Object.keys(R[plan]?R[plan].years:{}).map(Number).sort((a,b)=>b-a).forEach(y=>{const r=dres(plan,y,n);if(!r)return;[['pres','President'],['gov','Governor'],['sen','U.S. Senate']].forEach(([k,lab])=>{if(!r[k])return;const nm=names(plan,y,k);rows.push([y,lab,esc(nm[0])+' '+PCT(r[k][0]),esc(nm[1])+' '+PCT(r[k][1]),RM(r[k][0]-r[k][1])]);});});
  side.innerHTML=`<div class="detail"><button class="back" id="dback">← Back</button><span class="status">${esc((CM.plan(plan)||{}).label||plan)}</span><h2>${esc(CM.districtName(plan,n))}</h2><div class="sub">${cs.length} ${cs.length===1?'county':'counties'}</div><div class="cctab">${H('How this district voted')}<table class="cmp"><tr><th>Year</th><th>Race</th><th>Rep.</th><th>Dem.</th><th>Margin</th></tr>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</table><div class="ccnote">${esc((R[plan]||{}).basis||'')}.</div>${H('Counties in this district')}${cs.map(c=>CM.countyRow(c[0],PCT0(c[2]),c[2]<0.995?'part of the county':'')).join('')}</div></div>`;
  $('dback').onclick=()=>{CM.highlightDistrict(null);if(ST.f)showCounty(ST.f);else back();};}
function showPin(p){CM.select(p.id);CM.zoomPin(p);side.innerHTML=`<div class="detail" style="padding-bottom:0"><button class="back" id="pback">← Back</button></div>`+CM.pinHTML(p);$('pback').onclick=()=>{CM.select(null);if(ST.f)showCounty(ST.f);else back();};}
// ---- the roundtable brief ----
function briefHTML(f){const c=E.counties[f]||{},v=V[f];const k=know(f);const orgs=ORG[f]||[];const by={};orgs.forEach(o=>{(by[o.cat]=by[o.cat]||[]).push(o);});const bc=B.counties[f]||{cands:[]};const races={};bc.cands.forEach(i=>{const cd=B.cands[i],o=B.offices[cd[1]];if(DOWN.has(o[1])&&cd[3]!=null)(races[o[0]]=races[o[0]]||[]).push(cd);});
  const sec=(t,b)=>`<h2>${t}</h2>${b}`;const li=a=>`<ul>${a.map(x=>`<li>${x}</li>`).join('')}</ul>`;const parts=plan=>((X.counties[f]||{})[plan]||[]).map(([n,p,sh])=>'CD '+n+(sh<0.995?' ('+PCT0(sh)+')':'')).join(' + ')||'—';
  const srcs=[['Texas Secretary of State registration and canvass','https://www.sos.state.tx.us/elections/historical/vrfig.shtml'],['Texas Legislative Council plan and election reports','https://data.capitol.texas.gov/'],['Texas Demographic Center 2025 estimates','https://demographics.texas.gov/'],['U.S. Census Bureau ACS 2020-24','https://data.census.gov/'],['Texas Ethics Commission campaign finance (totals and itemized contributions)','https://www.ethics.state.tx.us/search/cf/'],['Federal Election Commission bulk data','https://www.fec.gov/data/browse-data/?tab=bulk-data'],['Texas Data Center Watch (via texasmaps.github.io)','https://texasmaps.github.io/texas_data_center_map.html'],['TWDB water data and PRISM rainfall','https://www.twdb.texas.gov/']].concat(orgs.map(o=>[o.org,o.src?o.src.split(' ')[0]:'']).filter(x=>x[1]));
  const seen=new Set();const srcList=srcs.filter(([t,u])=>{if(seen.has(u))return false;seen.add(u);return true;});
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(cname[f])} County roundtable brief</title><style>body{font:13px/1.45 -apple-system,"IBM Plex Sans",Helvetica,Arial,sans-serif;color:#161B26;max-width:820px;margin:24px auto;padding:0 20px}h1{font-size:22px;margin:0 0 2px}h2{font-size:13px;letter-spacing:.1em;text-transform:uppercase;color:#7A1F1F;border-bottom:1px solid #ddd;margin:16px 0 6px;padding-bottom:2px}ul{margin:4px 0 4px 18px;padding:0}li{margin:2px 0}.sub{color:#555;margin-bottom:8px}.st b{display:block}.st{margin:5px 0}.ev{color:#444;font-variant-numeric:tabular-nums}small{color:#666}@media print{body{margin:0;max-width:none}}</style></head><body>
<h1>${esc(cname[f])} County — roundtable brief</h1><div class="sub">${esc((RG[f]||{}).Region||'')} · prepared ${new Date().toISOString().slice(0,10)} from the Texas County Deep Dive · ${num(d(f,'Population, July 1 2025 (TDC prelim.)'))} people, ${num(e(f,'registered_2024'))} registered voters</div>
${sec('What to know',k.map(s=>`<div class="st"><b>${esc(s.t)}</b><span class="ev">${s.ev.map(([a,b])=>esc(a)+': '+esc(String(b))).join(' · ')}</span></div>`).join(''))}
${sec('Electorate and turnout',li([`Adults 18+: ${num(v.adults)}; registered March 2026: ${num(c.registered_march_2026)} (${PCT0(v.regOfAdults)} of adults; ${SPCT(c.registration_growth_2024_2026)} since Nov. 2024; ${num(c.suspense_march_2026)} on the suspense list); registered Nov. 2024: ${num(c.registered_2024)}; registration growth 2020-24 ${SPCT(c.registration_growth_2020_2024)} vs population growth 2020-25 ${SPCT(d(f,'Pop. change 2020-2025 (%)'))}`,`Turnout: 2024 ${PCT(c.turnout_2024)} (Texas ${PCT(S.turnout_2024)}); 2020 ${PCT(c.turnout_2020)}; 2022 ${PCT(c.turnout_2022)}; 2018 ${PCT(c.turnout_2018)}`,`Primary turnout 2018: ${c.primary_turnout_2018!=null?PCT(c.primary_turnout_2018):'—'} (Democratic share of primary votes ${c.primary_D_share_2018!=null?PCT(c.primary_D_share_2018):'—'})`]))}
${sec('Election change',li([`President 2024: Republican ${PCT(c.pres_R_2024)} (${num(c.pres_R_votes_2024)}), Democratic ${PCT(c.pres_D_2024)} (${num(c.pres_D_votes_2024)}), margin ${RMN(c.pres_margin_2024,2024,'pres')}`,`Trump share 2016 ${PCT(c.pres_R_2016)} → 2020 ${PCT(c.pres_R_2020)} → 2024 ${PCT(c.pres_R_2024)} (${PTS(c.pres_R_change_2020_2024)} since 2020; Texas ${PTS(S.pres_R_change_2020_2024)})`,`Governor 2022: Abbott ${PCT(c.gov_R_2022)}, O'Rourke ${PCT(c.gov_D_2022)}, margin ${RMN(c.gov_margin_2022,2022,'gov')} (2018: ${RMN(c.gov_margin_2018,2018,'gov')}; swing ${PTS(c.gov_margin_change_2018_2022)}); U.S. Senate 2024 ${RMN(c.sen_margin_2024,2024,'sen')}`]))}
${sec('Demographics and economy',li([`Population ${num(d(f,'Population, July 1 2025 (TDC prelim.)'))} (${SPCT(d(f,'Pop. change 2020-2025 (%)'))} since 2020); median age ${d(f,'Median age')}; Hispanic ${PCT(d(f,'Hispanic (%)'))}, White ${PCT(d(f,'Non-Hispanic White (%)'))}, Black ${PCT(d(f,'Non-Hispanic Black (%)'))}, Asian ${PCT(d(f,'Non-Hispanic Asian (%)'))}`,`Median household income ${USD(d(f,'Median household income ($)'))} (Texas ${USD(TXD['Median household income ($)'])}); poverty ${PCT(d(f,'Poverty rate (%)'))}; bachelor's or higher ${PCT(d(f,"Bachelor's degree or higher, 25+ (%)"))}; unemployment ${PCT(d(f,'Unemployment rate (%)'))}`,`Largest industries: ${topInd(f,4).map(x=>x[0]+' '+PCT0(x[1])).join('; ')}`]))}
${sec('Redistricting',li([`2024 map (PLANC2193): ${parts(OLD)} · 2026 map (PLANC2333): ${parts(NEW)} · residents with a new district number: ${PCT0(v.cdChg)}`,v.leanChg!=null?`2024 presidential vote under the old district ${RM(v.leanOld)}; re-tabulated into the 2026 district ${RM(v.leanNew)}`:'',`Legislative: ${['PLANH2316','PLANS2168','PLANE2106'].map(pl=>((X.counties[f]||{})[pl]||[]).map(([n,p,sh])=>CM.districtName(pl,n)+(sh<0.995?' ('+PCT0(sh)+')':'')).join(', ')).filter(Boolean).join(' · ')}`].filter(Boolean)))}
${sec('Contributions from county donors',(()=>{const g=[];Object.keys(CT.cands).forEach(i=>{const x=CT.cands[i][f];if(x&&x[0]>0)g.push([+i,x]);});g.sort((a,b)=>b[1][0]-a[1][0]);return `<p>Donors in the county gave ${USDK(v.contrib)} in itemized contributions to 2026 state candidates in 2026 (${num(v.contribN)} gifts): ${USDK(v.contribR)} to Republican and ${USDK(v.contribD)} to Democratic candidates${v.govDshare!=null?`; governor's race: ${PCT0(v.govDshare)} of the county's dollars to the Democratic candidate`:''}.</p>`+(g.length?li(g.slice(0,8).map(([i,x])=>`${esc(B.cands[i][0])} (${esc(B.cands[i][2])}), ${esc(title(B.offices[B.cands[i][1]][0]))}: ${USD(x[0])} in 2026, ${USD(x[2])} since 2025`)):'');})())}
${sec('Down-ballot races and fundraising',Object.keys(races).length?li(Object.entries(races).sort((a,b)=>b[1].reduce((x,y)=>x+(y[3]||0),0)-a[1].reduce((x,y)=>x+(y[3]||0),0)).map(([r,cs])=>`${esc(title(r))}: ${cs.sort((a,b)=>(b[3]||0)-(a[3]||0)).map(cd=>`${esc(cd[0])} (${esc(cd[2])}) raised ${USD(cd[3])}, cash ${cd[4]!=null?USD(cd[4]):'—'}, through ${esc(cd[5]||'—')}`).join('; ')}`)):'<p>No state-district race here has reported TEC money.</p>')}
${sec('2026 ballot and county chair',(()=>{const ch=bc.chair||{};const cp={},ord=[];bc.cands.forEach(i=>{const cd=B.cands[i],o=B.offices[cd[1]];if(o[1]==='County / precinct'){if(!cp[o[0]]){cp[o[0]]=[];ord.push(o[0]);}cp[o[0]].push(cd);}});return `<p>Democratic county chair: ${ch.name?esc(ch.name)+(ch.email?' · '+esc(ch.email):'')+(ch.phone?' · '+esc(ch.phone):''):esc(ch.status||'none listed')}. ${num(bc.cands.length)} candidates on the certified ballot (SOS, ${esc(B.ballot_cert)}).</p>`+(ord.length?li(ord.map(o=>`${esc(title(o))}: ${cp[o].map(cd=>esc(cd[0])+' ('+esc(cd[2])+')').join(', ')}${cp[o].length===1?' — unopposed':''}`)):'<p>No county or precinct races certified for this county.</p>');})())}
${sec('Community organizations / brokers',orgs.length?Object.keys(by).sort((a,b)=>CATS.indexOf(a)-CATS.indexOf(b)).map(ct=>`<b>${esc(ct)}</b>${li(by[ct].map(o=>`${esc(o.org)}${o.leader?' — '+esc(o.leader)+(o.title?', '+esc(o.title):''):''}${o.phone?' · '+esc(o.phone):''}${o.email?' · '+esc(o.email):''}${o.web?' · '+esc(o.web):''}${o.notes&&/verify/i.test(o.notes)?' <small>(auto-extracted; verify)</small>':''}`))}`).join(''):'<p>None collected yet for this county.</p>')}
${sec('Water context',li([`Rain, last 12 months: ${v.rainPct!=null?v.rainPct+'% of usual':'—'} (usual ${v.rain||'—'} in/yr); wells on record ${num(v.wells||0)}, drilled since 2020 ${num(v.wellsNew||0)}`,`Aquifers: ${aqList(f)}`]))}
${sec('Data-center activity',(DCC[f]||[]).length?li((DCC[f]||[]).map(s=>`${esc(s.name)} — ${esc(s.operator||'operator not listed')}, ${esc(s.status.replace('_',' '))}${s.mw?', '+num(s.mw)+' MW':''}${s.city?', '+esc(s.city):''}`)):'<p>No data center project tracked in this county.</p>')}
${sec('Sources',li(srcList.map(([t,u])=>`${esc(t)}: <a href="${esc(u)}">${esc(u)}</a>`)))}
<p><small>An organization does not control or perfectly represent its members; leader names marked "verify" were auto-extracted from websites. Results on the 2026 district lines are re-tabulations of past votes. Fundraising: TEC 2026 year to date; FEC 2025-26 cycle totals.</small></p></body></html>`;}
function openBrief(f){const html=briefHTML(f);const w=window.open('','_blank');if(w){w.document.open();w.document.write(html);w.document.close();}else{const a=document.createElement('a');a.href='data:text/html;charset=utf-8,'+encodeURIComponent(html);a.download=cname[f].replace(/\s+/g,'_')+'_County_roundtable_brief.html';a.click();}}
// ---- pins: data center projects ----
const PINS=DC.filter(s=>s.status!=='withdrawn'&&s.lat!=null).map(s=>({id:s.id,name:s.name,lon:s.lon,lat:s.lat,fips:s.fips,county:s.county,city:s.city,status:s.status,size:s.mw||0,hot:!!s.hot,sub:s.operator||'',details:{'Status':s.status.replace('_',' '),'Announced power':s.mw?num(s.mw)+' MW':'not reported','Acres':s.acres?num(s.acres):null},url:'texas_data_center_map.html#pin='+encodeURIComponent(s.id),urlLabel:'Data center map'}));
// ---- start ----
const hh=decodeURIComponent(location.hash||'').replace(/^#/,'');const hv=k=>{const m=new RegExp('(?:^|&)'+k+'=([^&]+)').exec(hh);return m?m[1]:'';};
if(hv('lock')==='1')ST.lock=true;if(hv('color'))ST.lastBase=hv('color');if(hv('compare'))ST.cmp=hv('compare').split(',').filter(x=>DM[x]).slice(0,3);if(hv('tab'))ST.tab=hv('tab');
CM.init({metrics:METRICS,base:hv('color')&&METRICS.some(m=>m.key===hv('color'))?hv('color'):(TABDEF[ST.tab]||'pop_change'),plan:hv('lines')||'',pins:PINS,showPins:hv('color').startsWith('dc_')||(hv('layers')||'').split(',').includes('dots'),pinStatuses:{operating:{label:'Operating',color:'#3B5B8C'},under_construction:{label:'Under construction',color:'#C8842A'},proposed:{label:'Proposed',color:'#A3262A'}},pinLabel:'Data center projects',pinSingular:'project',pinPlural:'projects',hotLabel:'Red ring: flagged project',
  controls:[],pages:[['texas_county_maps.html','County maps (topics)'],['texas_data_center_map.html','Data centers'],['texas_aquifers_map.html','Aquifers'],['texas_rainfall_map.html','Rainfall'],['texas_wells_map.html','Wells']],here:'texas_county_deep_dive.html',noWelcome:true,
  onCounty:showCounty,onDistrict:showDistrict,onPin:showPin,onBackground:()=>{},onUpdate:()=>{renderContents();renderRibbon();},onView:updateScale,
  about:'<p><b>A guided county command center.</b> Search a place, read what changed in plain English, check the exact numbers underneath, compare counties, find the organized local institutions, see water and data-center pressures, and prepare a roundtable brief. Everything on the map is one county measure at a time; congressional lines can be drawn over any coloring.</p>',
  sources:'<ul><li><b>Electorate and elections</b>: Texas Secretary of State registration figures, official canvass 2006-2018 and county race pages for the 2014-2018 primaries; Texas Legislative Council Red-211 county subtotals 2020-2024.</li><li><b>Districts</b>: TLC plans PLANC2333, PLANC2193, PLANH2316, PLANS2168, PLANE2106 with Red-100 and Red-206 reports; 2020 Census PL 94-171 blocks.</li><li><b>Demographics</b>: Texas Demographic Center preliminary Vintage 2025; ACS 2020-24 five-year.</li><li><b>Money</b>: Texas Ethics Commission bulk export as of 2026-09-26 (totals from cover sheets; contributions by county from the itemized Schedule A rows, placed by the donor\'s ZIP or city); FEC bulk candidate summary as of 2026-09-28; SOS ballot certification of 2026-08-28.</li><li><b>Community organizations</b>: IPEDS, CMS, TCCE, Texas AFT, TSTA, Texas AFL-CIO, Texas REALTORS, Texas Farm Bureau, American Legion Department of Texas; each row carries its source.</li><li><b>Water</b>: PRISM rainfall; TWDB wells and the TWDB major and minor aquifer outlines drawn by the Aquifers overlay.</li><li><b>Data centers</b>: Texas Data Center Watch.</li><li><b>Places</b>: U.S. Census Bureau 2024 Gazetteer.</li></ul>',
  caveats:'<ul><li>Comparisons are like for like (presidential with presidential, midterm with midterm), in points.</li><li>Results on the 2026 district lines are re-tabulations of past votes, not elections held under them.</li><li>Down-ballot money counts a district race in full for every county the district touches; TEC figures are 2026 year to date, FEC figures are 2025-26 cycle totals; county offices are blank.</li><li>An organization does not control or perfectly represent its members; leader names marked "verify" were auto-extracted from websites.</li><li>Aquifer shares are approximate (grid sampling of generalized outlines).</li></ul>'});
renderTabs();renderRibbon();renderTray();renderContents();updateScale();$('side-title').textContent='Texas';$('loading').remove();
$('stats').innerHTML=[[num(S.registered_march_2026),'registered voters, March 2026'],[RM(S.pres_margin_2024),'2024 presidential margin'],[PTS(S.turnout_change_2018_2022),'midterm turnout change 2018 to 2022']].map(([v,l])=>CM.stat(v,l)).join('');
if(hv('county')&&DM[hv('county')])showCounty(hv('county'));else renderPanel();
if(hv('district')){const m=/^([A-Za-z0-9]+):(\d+)$/.exec(hv('district'));if(m)showDistrict(m[1],+m[2]);}
window.TX_DEEP_DIVE={ST,showCounty,addCompare,openBrief,know,briefHTML};
})();
